import React, { useState } from 'react';
import CodeEditorPanel from '@/components/tools/CodeEditorPanel';

export const JsonToGo = () => {
  const [input, setInput] = useState('{\n  "user_id": 1001,\n  "email": "dev@example.com",\n  "verified": true,\n  "scores": [98, 100]\n}');
  const [goOutput, setGoOutput] = useState('');
  const [error, setError] = useState('');

  const toPascalCase = (str) => {
    return str.split(/[\s_\-]+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  };

  const generateGoStruct = (obj, structName = 'AutoGenerated') => {
    let result = `type ${structName} struct {\n`;
    Object.entries(obj).forEach(([key, val]) => {
      const fieldName = toPascalCase(key);
      let typeStr = 'interface{}';
      if (val === null) typeStr = 'interface{}';
      else if (typeof val === 'boolean') typeStr = 'bool';
      else if (typeof val === 'number') typeStr = Number.isInteger(val) ? 'int' : 'float64';
      else if (typeof val === 'string') typeStr = 'string';
      else if (Array.isArray(val)) {
        const elemType = val.length > 0 ? typeof val[0] === 'number' ? (Number.isInteger(val[0]) ? 'int' : 'float64') : typeof val[0] : 'interface{}';
        typeStr = `[]${elemType}`;
      }
      result += `\t${fieldName} ${typeStr} \`json:"${key}"\`\n`;
    });
    result += '}';
    return result;
  };

  React.useEffect(() => {
    if (!input.trim()) {
      setGoOutput('');
      setError('');
      return;
    }
    try {
      const parsed = JSON.parse(input);
      setGoOutput(generateGoStruct(parsed));
      setError('');
    } catch (err) {
      setError(`JSON Error: ${err.message}`);
      setGoOutput('');
    }
  }, [input]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      {error && (
        <div style={{ padding: '0.75rem 1rem', background: 'var(--status-danger-bg)', color: 'var(--status-danger)', borderRadius: '6px', fontSize: '0.875rem' }}>
          {error}
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
        <CodeEditorPanel
          title="JSON Input"
          value={input}
          onChange={setInput}
        />
        <CodeEditorPanel
          title="Golang Struct Output"
          value={goOutput}
          readOnly
        />
      </div>
    </div>
  );
};

export default JsonToGo;
