export const toolsRegistry = [
  // -------------------------------------------------------------
  // JSON & DATA (11 Active)
  // -------------------------------------------------------------
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    category: 'json-data',
    description: 'Format, beautify, and inspect raw JSON data with customizable indentation (2 spaces, 4 spaces, or tabs) and instant syntax error detection.',
    shortDescription: 'Format and beautify raw JSON data.',
    icon: 'FileJson',
    keywords: ['json formatter', 'json beautifier', 'format json', 'json pretty printer', 'json parser'],
    primaryKeyword: 'JSON Formatter',
    relatedKeywords: ['JSON beautifier', 'format JSON online', 'JSON pretty print', 'indent JSON'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: false,
    component: 'JsonFormatter',
    seoTitle: 'JSON Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format, beautify, and parse raw JSON strings instantly in your web browser. Privacy-focused local processing with zero server uploads.',
    howItWorks: 'Paste your unformatted or minified JSON string into the input area. Select your preferred indentation spacing and click Format JSON.',
    features: [
      'Configurable indentation spacing (2 spaces, 4 spaces, tab indentation)',
      'Real-time syntax validation with exact error diagnostics',
      'One-click copy to clipboard and sample data loading',
      '100% browser-local execution with zero data transmission'
    ],
    useCases: [
      'Formatting minified API responses for debugging',
      'Inspecting complex configuration files like package.json',
      'Validating nested payload structures before backend integration'
    ],
    examples: [
      {
        title: 'Beautify Minified JSON Payload',
        input: '{"service":"HMDevTools","active":true}',
        output: '{\n  "service": "HMDevTools",\n  "active": true\n}'
      }
    ],
    faq: [
      { question: 'Is my JSON payload transmitted to any server?', answer: 'No. Formatting is computed 100% locally in your browser JavaScript memory context.' }
    ],
    relatedTools: ['json-validator', 'json-minifier', 'json-viewer', 'json-to-xml', 'json-to-typescript']
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    slug: 'json-validator',
    category: 'json-data',
    description: 'Validate JSON syntax compliance against RFC 8259 specifications with exact error locations.',
    shortDescription: 'Validate JSON syntax and RFC 8259 compliance.',
    icon: 'CheckCircle2',
    keywords: ['json validator', 'validate json', 'json syntax checker', 'rfc 8259 validator'],
    primaryKeyword: 'JSON Validator',
    relatedKeywords: ['validate JSON online', 'JSON syntax checker', 'RFC 8259 compliance'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: false,
    component: 'JsonValidator',
    seoTitle: 'JSON Validator & Syntax Checker Online | HMDevTools',
    seoDescription: 'Validate your JSON strings against official RFC 8259 specifications with instant syntax diagnostics.',
    howItWorks: 'Paste your JSON data into the editor to check quote placement, bracket balancing, and data types.',
    features: ['Instant validation status', 'Detailed syntax error reporting', 'Browser local execution'],
    useCases: ['Verifying webhook payloads', 'Catching syntax bugs in REST API responses'],
    examples: [{ title: 'Valid RFC 8259 JSON', input: '{"status": "ok", "code": 200}' }],
    faq: [{ question: 'What JSON standards are validated?', answer: 'Strict RFC 8259 rules including double-quoted keys and boolean literals.' }],
    relatedTools: ['json-formatter', 'json-minifier', 'json-viewer']
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    slug: 'json-minifier',
    category: 'json-data',
    description: 'Compress and minify raw JSON by stripping whitespace and newlines for minimal payload transfer size.',
    shortDescription: 'Minify and compress JSON strings.',
    icon: 'Minimize2',
    keywords: ['json minifier', 'minify json', 'compress json'],
    primaryKeyword: 'JSON Minifier',
    relatedKeywords: ['compress JSON', 'strip JSON whitespace'],
    status: 'active',
    processingMode: 'client',
    component: 'JsonMinifier',
    seoTitle: 'JSON Minifier & Compressor Online | HMDevTools',
    seoDescription: 'Compress and minify JSON strings instantly in your browser to reduce network transfer size.',
    howItWorks: 'Paste formatted JSON into the input box to output a single-line minified string.',
    features: ['Strips unneeded indentation', 'Reduces HTTP payload sizes'],
    useCases: ['Minifying configuration objects for web requests'],
    examples: [{ title: 'Minify Example', input: '{\n  "foo": "bar"\n}', output: '{"foo":"bar"}' }],
    faq: [{ question: 'Does minifying alter payload values?', answer: 'No, minifying only removes non-semantic whitespace.' }],
    relatedTools: ['json-formatter', 'json-validator']
  },
  {
    id: 'json-viewer',
    name: 'JSON Viewer',
    slug: 'json-viewer',
    category: 'json-data',
    description: 'Interactive tree viewer to explore nested JSON objects and arrays with expand/collapse nodes.',
    shortDescription: 'Interactive tree view for nested JSON.',
    icon: 'Eye',
    keywords: ['json viewer', 'json tree view', 'inspect json'],
    primaryKeyword: 'JSON Viewer',
    relatedKeywords: ['inspect JSON', 'collapsible JSON tree'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonViewer',
    seoTitle: 'Interactive JSON Viewer & Inspector | HMDevTools',
    seoDescription: 'Explore deep nested JSON objects and arrays with an interactive collapsible tree view.',
    howItWorks: 'Paste raw JSON to render an interactive node tree representation.',
    features: ['Collapsible object and array nodes', 'Color-coded data types'],
    useCases: ['Exploring complex multi-level API responses'],
    examples: [{ title: 'Nested JSON', input: '{"user":{"id":1,"roles":["admin"]}}' }],
    faq: [{ question: 'Can I expand/collapse nested nodes?', answer: 'Yes, click any node header to toggle.' }],
    relatedTools: ['json-formatter', 'json-to-xml']
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    slug: 'json-to-csv',
    category: 'json-data',
    description: 'Convert JSON object arrays into tabular CSV format for spreadsheets and data imports.',
    shortDescription: 'Convert JSON arrays to CSV spreadsheets.',
    icon: 'FileSpreadsheet',
    keywords: ['json to csv', 'convert json to csv', 'export csv'],
    primaryKeyword: 'JSON to CSV',
    relatedKeywords: ['convert JSON array to CSV', 'export JSON to Excel'],
    status: 'active',
    processingMode: 'client',
    component: 'JsonToCsv',
    seoTitle: 'JSON to CSV Converter Online | HMDevTools',
    seoDescription: 'Convert JSON object arrays into clean CSV format for Excel or Google Sheets locally.',
    howItWorks: 'Paste a JSON array of objects to extract property headers and convert rows into comma-separated values.',
    features: ['Extracts CSV header row', 'Handles quotes and commas correctly'],
    useCases: ['Converting API datasets into CSV for Excel analysis'],
    examples: [{ title: 'JSON Array to CSV', input: '[{"name":"Alice","age":30}]', output: 'name,age\nAlice,30' }],
    faq: [{ question: 'Does it handle commas in text fields?', answer: 'Yes, fields containing commas are wrapped in quotes.' }],
    relatedTools: ['csv-to-json', 'json-to-yaml', 'json-to-xml']
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    slug: 'csv-to-json',
    category: 'json-data',
    description: 'Parse CSV tabular spreadsheets into structured JSON object arrays.',
    shortDescription: 'Parse CSV text into structured JSON.',
    icon: 'FileCode',
    keywords: ['csv to json', 'convert csv to json', 'parse csv'],
    primaryKeyword: 'CSV to JSON',
    relatedKeywords: ['parse CSV string', 'convert spreadsheet to JSON'],
    status: 'active',
    processingMode: 'client',
    component: 'CsvToJson',
    seoTitle: 'CSV to JSON Converter Online | HMDevTools',
    seoDescription: 'Convert CSV tabular data into structured JSON array objects locally.',
    howItWorks: 'Paste comma-separated rows with a header row to generate JSON objects.',
    features: ['Header row parsing', 'Trims whitespace and quotes'],
    useCases: ['Converting exported spreadsheets into JSON for web apps'],
    examples: [{ title: 'CSV to JSON', input: 'id,name\n101,Dev', output: '[\n  {\n    "id": "101",\n    "name": "Dev"\n  }\n]' }],
    faq: [{ question: 'What delimiter is expected?', answer: 'Commas are standard.' }],
    relatedTools: ['json-to-csv', 'json-formatter']
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    slug: 'json-to-yaml',
    category: 'json-data',
    description: 'Convert JSON documents into human-readable YAML configurations for Docker and Kubernetes.',
    shortDescription: 'Convert JSON into clean YAML format.',
    icon: 'FileText',
    keywords: ['json to yaml', 'convert json to yaml', 'k8s yaml'],
    primaryKeyword: 'JSON to YAML',
    relatedKeywords: ['convert JSON to YAML', 'Kubernetes YAML generator'],
    status: 'active',
    processingMode: 'client',
    component: 'JsonToYaml',
    seoTitle: 'JSON to YAML Converter Online | HMDevTools',
    seoDescription: 'Convert JSON structures to YAML configurations instantly for Kubernetes and Docker.',
    howItWorks: 'Paste JSON content to generate formatted YAML output.',
    features: ['Clean YAML 2-space indentation', 'Supports nested objects and arrays'],
    useCases: ['Converting JSON configs to Kubernetes manifests'],
    examples: [{ title: 'JSON to YAML', input: '{"service":"web"}' }],
    faq: [{ question: 'Which YAML version is generated?', answer: 'YAML 1.2 compliant key-value structures.' }],
    relatedTools: ['yaml-to-json', 'json-to-xml']
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    slug: 'yaml-to-json',
    category: 'json-data',
    description: 'Convert YAML configuration files into valid JSON data structures.',
    shortDescription: 'Convert YAML configs into valid JSON.',
    icon: 'FileJson',
    keywords: ['yaml to json', 'convert yaml to json', 'yaml parser'],
    primaryKeyword: 'YAML to JSON',
    relatedKeywords: ['parse YAML online', 'convert YAML to JSON'],
    status: 'active',
    processingMode: 'client',
    component: 'YamlToJson',
    seoTitle: 'YAML to JSON Converter Online | HMDevTools',
    seoDescription: 'Parse YAML configurations into formatted JSON objects in your browser.',
    howItWorks: 'Paste YAML key-value pairs to calculate equivalent JSON data.',
    features: ['Parses strings, numbers, booleans, and nested structures'],
    useCases: ['Converting CI/CD YAML files to JSON'],
    examples: [{ title: 'YAML to JSON', input: 'name: HMDevTools' }],
    faq: [{ question: 'Are YAML comments included?', answer: 'No, comments are stripped as JSON does not support comments.' }],
    relatedTools: ['json-to-yaml', 'json-formatter']
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    slug: 'json-to-xml',
    category: 'json-data',
    description: 'Convert JSON objects and arrays into structured, properly formatted XML documents with customizable root elements.',
    shortDescription: 'Convert JSON objects into formatted XML.',
    icon: 'FileCode',
    keywords: ['json to xml', 'convert json to xml', 'json xml converter', 'export xml'],
    primaryKeyword: 'JSON to XML',
    relatedKeywords: ['convert JSON object to XML', 'JSON XML transformer', 'export JSON as XML'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'JsonToXml',
    seoTitle: 'JSON to XML Converter Online | HMDevTools',
    seoDescription: 'Convert JSON objects and arrays into structured XML documents with XML entity escaping and custom root elements.',
    howItWorks: 'Paste a JSON payload, enter your preferred root tag name, and convert your data into clean XML markup.',
    features: [
      'Configurable root element tag name',
      'Automatic XML entity escaping (&, <, >, ", \')',
      'Handles nested objects and arrays of items',
      '100% browser-local execution'
    ],
    useCases: [
      'Converting REST API JSON payloads to SOAP / XML web services',
      'Transforming JSON dataset exports into XML configuration files',
      'Preparing XML feeds for legacy enterprise backends'
    ],
    examples: [
      { title: 'JSON Object to XML', input: '{"title":"DevTools","version":1}', output: '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  <title>DevTools</title>\n  <version>1</version>\n</root>' }
    ],
    faq: [
      { question: 'How are arrays handled?', answer: 'Array elements are converted into repeated child XML elements.' }
    ],
    relatedTools: ['xml-to-json', 'xml-formatter', 'json-formatter', 'json-to-yaml']
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    slug: 'xml-to-json',
    category: 'json-data',
    description: 'Parse XML documents and elements into structured JSON object representations.',
    shortDescription: 'Parse XML documents into JSON objects.',
    icon: 'FileJson',
    keywords: ['xml to json', 'convert xml to json', 'parse xml', 'xml parser'],
    primaryKeyword: 'XML to JSON',
    relatedKeywords: ['parse XML online', 'convert XML to JSON object', 'XML data parser'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'XmlToJson',
    seoTitle: 'XML to JSON Converter Online | HMDevTools',
    seoDescription: 'Parse XML files and string documents into formatted JSON objects locally in your web browser.',
    howItWorks: 'Paste XML content into the editor to parse elements, attributes, and text nodes into JSON.',
    features: [
      'Parses XML tags, attributes (@attributes), and text nodes',
      'Handles repeated XML sibling tags as JSON arrays',
      'Provides line-level XML syntax validation error messages'
    ],
    useCases: [
      'Transforming legacy XML API responses into modern JSON payloads',
      'Extracting data fields from RSS or Atom XML feeds',
      'Converting XML config files for JavaScript frontends'
    ],
    examples: [
      { title: 'XML to JSON Parsing', input: '<root><item>Hello</item></root>', output: '{\n  "root": {\n    "item": "Hello"\n  }\n}' }
    ],
    faq: [
      { question: 'How are XML attributes preserved?', answer: 'Attributes are extracted into a special "@attributes" object key.' }
    ],
    relatedTools: ['json-to-xml', 'xml-formatter', 'json-formatter']
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    slug: 'xml-formatter',
    category: 'json-data',
    description: 'Beautify and format unindented or minified XML files with clean tag indentation and attribute alignment.',
    shortDescription: 'Beautify and format XML markup.',
    icon: 'Code',
    keywords: ['xml formatter', 'beautify xml', 'format xml', 'xml prettifier'],
    primaryKeyword: 'XML Formatter',
    relatedKeywords: ['beautify XML document', 'format XML online', 'XML pretty print'],
    status: 'active',
    processingMode: 'client',
    isPopular: false,
    isNew: true,
    component: 'XmlFormatter',
    seoTitle: 'XML Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format and beautify raw XML documents with clean tag indentation and line breaks locally in your browser.',
    howItWorks: 'Paste raw XML string markup to auto-format element hierarchy with consistent 2-space indentation.',
    features: [
      'Clean 2-space element tag indentation',
      'Preserves self-closing elements and attributes',
      'Safety length guards for large XML documents'
    ],
    useCases: [
      'Formatting compressed XML API logs for inspection',
      'Cleaning up single-line XML configuration files',
      'Beautifying SOAP payload messages'
    ],
    examples: [
      { title: 'Raw XML Beautify', input: '<user><id>1</id><name>Alice</name></user>', output: '<user>\n  <id>1</id>\n  <name>Alice</name>\n</user>' }
    ],
    faq: [
      { question: 'Does formatting modify XML tag values?', answer: 'No, tag content and attributes are preserved unchanged.' }
    ],
    relatedTools: ['json-to-xml', 'xml-to-json', 'html-formatter']
  },

  // -------------------------------------------------------------
  // ENCODING & DECODING (8 Active)
  // -------------------------------------------------------------
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder',
    slug: 'base64-encoder',
    category: 'encoding',
    description: 'Encode plain text or multi-byte UTF-8 strings into standard Base64 format.',
    shortDescription: 'Encode plain text into Base64 format.',
    icon: 'Binary',
    keywords: ['base64 encoder', 'encode base64', 'base64 string'],
    primaryKeyword: 'Base64 Encoder',
    relatedKeywords: ['encode to Base64', 'UTF-8 Base64 encoder'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'Base64Encoder',
    seoTitle: 'Base64 Encoder Online | HMDevTools',
    seoDescription: 'Encode text strings and UTF-8 characters to Base64 format locally in your web browser.',
    howItWorks: 'Paste text or strings to compute Base64 encoded output instantly.',
    features: ['UTF-8 and Unicode character support', 'Real-time encoding output'],
    useCases: ['Encoding basic auth headers', 'Preparing data URLs for HTML/CSS embedding'],
    examples: [{ title: 'Text to Base64', input: 'Hello World', output: 'SGVsbG8gV29ybGQ=' }],
    faq: [{ question: 'Does it support Unicode and emojis?', answer: 'Yes, full UTF-8 byte array handling ensures special characters encode correctly.' }],
    relatedTools: ['base64-decoder', 'url-encoder', 'jwt-decoder', 'html-encoder']
  },
  {
    id: 'base64-decoder',
    name: 'Base64 Decoder',
    slug: 'base64-decoder',
    category: 'encoding',
    description: 'Decode Base64 encoded strings back into human-readable text and UTF-8 characters.',
    shortDescription: 'Decode Base64 strings back to text.',
    icon: 'Binary',
    keywords: ['base64 decoder', 'decode base64', 'base64 to text'],
    primaryKeyword: 'Base64 Decoder',
    relatedKeywords: ['decode Base64 online', 'Base64 to text'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'Base64Decoder',
    seoTitle: 'Base64 Decoder Online | HMDevTools',
    seoDescription: 'Decode Base64 strings back into original text or UTF-8 characters safely in your browser.',
    howItWorks: 'Paste Base64 encoded content to see decoded plain text immediately.',
    features: ['Decodes standard and URL-safe Base64', 'Detects malformed Base64 padding errors'],
    useCases: ['Decoding authorization header tokens', 'Inspecting parameter values'],
    examples: [{ title: 'Base64 to Text', input: 'SGVsbG8gV29ybGQ=', output: 'Hello World' }],
    faq: [{ question: 'What happens if input is invalid Base64?', answer: 'A clear decoding error message will alert you.' }],
    relatedTools: ['base64-encoder', 'jwt-decoder', 'url-decoder', 'html-decoder']
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder',
    slug: 'url-encoder',
    category: 'encoding',
    description: 'Encode characters in URLs into percent-encoded format for safe web transmission.',
    shortDescription: 'Percent-encode special characters in URLs.',
    icon: 'Link',
    keywords: ['url encoder', 'percent encoding', 'uri encode'],
    primaryKeyword: 'URL Encoder',
    relatedKeywords: ['percent encode URL', 'encodeURIComponent online'],
    status: 'active',
    processingMode: 'client',
    component: 'UrlEncoder',
    seoTitle: 'URL Encoder (Percent Encoding) Online | HMDevTools',
    seoDescription: 'Encode query parameters and URLs using RFC 3986 percent-encoding in your browser.',
    howItWorks: 'Paste query parameter values or URLs to encode special characters.',
    features: ['Supports encodeURIComponent and encodeURI modes', 'Encodes spaces to %20'],
    useCases: ['Encoding search queries for URL parameters'],
    examples: [{ title: 'Query Parameter Encoding', input: 'hello world & foo=bar', output: 'hello%20world%20%26%20foo%3Dbar' }],
    faq: [{ question: 'Difference between encodeURI and encodeURIComponent?', answer: 'encodeURI preserves URL structure (: / ? #), encodeURIComponent encodes all non-alphanumeric chars.' }],
    relatedTools: ['url-decoder', 'url-parser', 'html-encoder']
  },
  {
    id: 'url-decoder',
    name: 'URL Decoder',
    slug: 'url-decoder',
    category: 'encoding',
    description: 'Decode percent-encoded URL strings back into plain unescaped text.',
    shortDescription: 'Decode percent-encoded URL strings.',
    icon: 'Link2Off',
    keywords: ['url decoder', 'percent decode', 'uri decode'],
    primaryKeyword: 'URL Decoder',
    relatedKeywords: ['percent decode URL', 'decodeURIComponent online'],
    status: 'active',
    processingMode: 'client',
    component: 'UrlDecoder',
    seoTitle: 'URL Decoder Online | HMDevTools',
    seoDescription: 'Decode percent-encoded URL strings back into readable text locally in your web browser.',
    howItWorks: 'Paste percent-encoded URL strings to decode %20 and special characters.',
    features: ['Decodes %20 and percent sequences'],
    useCases: ['Decoding incoming tracking parameters from logs'],
    examples: [{ title: 'Percent Decoded', input: 'hello%20world%21', output: 'hello world!' }],
    faq: [{ question: 'Does it decode + as spaces?', answer: 'Standard decodeURIComponent converts percent codes.' }],
    relatedTools: ['url-encoder', 'url-parser', 'html-decoder']
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    category: 'encoding',
    description: 'Decode JSON Web Tokens (JWT) to inspect header claims, payload values, and expiration timestamps.',
    shortDescription: 'Inspect header, payload, and claims of JWTs.',
    icon: 'Key',
    keywords: ['jwt decoder', 'decode jwt', 'json web token', 'jwt inspector'],
    primaryKeyword: 'JWT Decoder',
    relatedKeywords: ['decode JWT online', 'JWT payload inspector'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JwtDecoder',
    seoTitle: 'JWT Decoder & Claims Inspector Online | HMDevTools',
    seoDescription: 'Decode JSON Web Tokens safely in your browser. Inspect header claims and token expiration without sending keys to any server.',
    howItWorks: 'Paste a 3-part JWT token to view decoded JSON header and payload claims.',
    features: ['Decodes header and payload claims', 'Checks exp timestamp expiration status', 'Security disclaimer banner'],
    useCases: ['Inspecting user roles inside OAuth tokens', 'Checking token expiration time'],
    examples: [{ title: 'Sample JWT', input: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c' }],
    faq: [{ question: 'Does decoding verify signature?', answer: 'No, decoding extracts claims. Verification requires secret keys on your server.' }],
    relatedTools: ['base64-decoder', 'uuid-generator', 'hash-generator']
  },
  {
    id: 'html-encoder',
    name: 'HTML Encoder',
    slug: 'html-encoder',
    category: 'encoding',
    description: 'Convert special HTML characters (&, <, >, ", \') into HTML entities to prevent XSS and rendering errors.',
    shortDescription: 'Convert special characters into HTML entities.',
    icon: 'Code',
    keywords: ['html encoder', 'escape html', 'html entity encoder', 'html escape'],
    primaryKeyword: 'HTML Encoder',
    relatedKeywords: ['escape HTML entities online', 'HTML entity encoder', 'escape HTML code'],
    status: 'active',
    processingMode: 'client',
    isPopular: false,
    isNew: true,
    component: 'HtmlEncoder',
    seoTitle: 'HTML Encoder (Entity Escaper) Online | HMDevTools',
    seoDescription: 'Escape special HTML characters into entity codes (&lt;, &gt;, &amp;, &quot;) locally in your web browser.',
    howItWorks: 'Type or paste raw HTML markup to escape reserved characters into safe HTML entity format.',
    features: ['Escapes <, >, &, ", and \'', 'Prevents HTML injection and XSS', 'Browser local execution'],
    useCases: ['Escaping user input for safe HTML display', 'Preparing code snippets for web tutorials'],
    examples: [{ title: 'Escape HTML Tags', input: '<div class="test">Hello & Welcome</div>', output: '&lt;div class=&quot;test&quot;&gt;Hello &amp; Welcome&lt;/div&gt;' }],
    faq: [{ question: 'Why escape HTML characters?', answer: 'Escaping reserved characters prevents browsers from interpreting text as executable HTML tags.' }],
    relatedTools: ['html-decoder', 'url-encoder', 'markdown-to-html']
  },
  {
    id: 'html-decoder',
    name: 'HTML Decoder',
    slug: 'html-decoder',
    category: 'encoding',
    description: 'Convert HTML entities (&lt;, &gt;, &amp;, &quot;) back into plain text and raw HTML characters.',
    shortDescription: 'Decode HTML entities back to plain text.',
    icon: 'Code',
    keywords: ['html decoder', 'unescape html', 'html entity decoder'],
    primaryKeyword: 'HTML Decoder',
    relatedKeywords: ['unescape HTML entities', 'decode HTML entity codes'],
    status: 'active',
    processingMode: 'client',
    isPopular: false,
    isNew: true,
    component: 'HtmlDecoder',
    seoTitle: 'HTML Decoder (Entity Unescaper) Online | HMDevTools',
    seoDescription: 'Convert HTML entity codes back into readable plain text and unescaped characters in your browser.',
    howItWorks: 'Paste HTML entity strings into the input box to unescape entity codes.',
    features: ['Decodes named entities (&lt;, &gt;, &amp;)', 'Supports numeric and hexadecimal entities'],
    useCases: ['Reading unescaped HTML content from database dumps', 'Decoding web scraper outputs'],
    examples: [{ title: 'Unescape HTML', input: '&lt;p&gt;Hello&lt;/p&gt;', output: '<p>Hello</p>' }],
    faq: [{ question: 'Does it support numeric entities?', answer: 'Yes, both named (&quot;) and numeric (&#34;) entities are decoded.' }],
    relatedTools: ['html-encoder', 'url-decoder', 'html-to-markdown']
  },
  {
    id: 'unicode-converter',
    name: 'Unicode Converter',
    slug: 'unicode-converter',
    category: 'encoding',
    description: 'Convert text to Unicode escape sequences (\\uXXXX) and convert Unicode escapes back to human-readable text.',
    shortDescription: 'Convert text to \\uXXXX Unicode escape sequences.',
    icon: 'Binary',
    keywords: ['unicode converter', 'unicode escape', 'text to unicode', 'decode unicode'],
    primaryKeyword: 'Unicode Converter',
    relatedKeywords: ['convert text to Unicode escape', 'decode \\uXXXX online'],
    status: 'active',
    processingMode: 'client',
    isPopular: false,
    isNew: true,
    component: 'UnicodeConverter',
    seoTitle: 'Unicode Escape Converter (\\uXXXX) Online | HMDevTools',
    seoDescription: 'Convert text and emojis to Unicode escape sequences (\\uXXXX) and back locally in your browser.',
    howItWorks: 'Switch between Encode and Decode modes to convert characters to \\uXXXX escape strings.',
    features: ['Supports UTF-8 and UTF-16 surrogate pairs (emojis)', 'Bidirectional conversion'],
    useCases: ['Escaping special characters in JSON / JavaScript strings', 'Debugging multi-byte string encoding'],
    examples: [{ title: 'Text to Unicode Escape', input: 'Hello 🚀', output: 'Hello \\ud83d\\ude80' }],
    faq: [{ question: 'Does it support emojis?', answer: 'Yes, emojis are converted into valid UTF-16 surrogate pair escape codes.' }],
    relatedTools: ['base64-encoder', 'html-encoder', 'url-encoder']
  },

  // -------------------------------------------------------------
  // GENERATORS (4 Active)
  // -------------------------------------------------------------
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    category: 'generators',
    description: 'Generate bulk cryptographically secure UUID v4 (Universally Unique Identifiers) in lowercase or uppercase.',
    shortDescription: 'Generate secure Version 4 UUIDs.',
    icon: 'Fingerprint',
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'random uuid'],
    primaryKeyword: 'UUID Generator',
    relatedKeywords: ['RFC 4122 UUID v4', 'GUID generator online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'UuidGenerator',
    seoTitle: 'UUID v4 / GUID Generator Online | HMDevTools',
    seoDescription: 'Generate random RFC 4122 Version 4 UUIDs and GUIDs in bulk locally using Web Crypto.',
    howItWorks: 'Select quantity and format preferences to generate unique RFC 4122 v4 UUIDs.',
    features: ['Web Crypto API randomness', 'Bulk generation up to 100 UUIDs', 'Uppercase toggle'],
    useCases: ['Generating database primary keys', 'Creating transaction tracking IDs'],
    examples: [{ title: 'Single UUID v4', output: 'f47ac10b-58cc-4372-a567-0e02b2c3d479' }],
    faq: [{ question: 'Are UUIDs cryptographically random?', answer: 'Yes, generated using window.crypto.getRandomValues.' }],
    relatedTools: ['password-generator', 'hash-generator', 'jwt-decoder']
  },
  {
    id: 'password-generator',
    name: 'Random Password Generator',
    slug: 'password-generator',
    category: 'generators',
    description: 'Generate strong, customizable passwords with configurable length, symbols, numbers, and entropy calculation.',
    shortDescription: 'Generate cryptographically strong passwords.',
    icon: 'ShieldCheck',
    keywords: ['password generator', 'random password', 'strong password'],
    primaryKeyword: 'Password Generator',
    relatedKeywords: ['strong password generator', 'random string generator'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'PasswordGenerator',
    seoTitle: 'Random Password Generator Online | HMDevTools',
    seoDescription: 'Generate strong random passwords locally using Web Crypto API with customizable character sets.',
    howItWorks: 'Adjust length slider and toggle uppercase, numbers, and symbol character sets.',
    features: ['Web Crypto API randomness', 'Length control (8-64 chars)', 'Character set toggles'],
    useCases: ['Generating database and server passwords', 'Creating secure API secrets'],
    examples: [{ title: '16 Char Password', output: 'k9#mP2$xL8!vQ4@z' }],
    faq: [{ question: 'Are passwords saved on a server?', answer: 'Never. Passwords are generated in client JS memory and wiped when closed.' }],
    relatedTools: ['uuid-generator', 'hash-generator', 'base64-encoder']
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    slug: 'lorem-ipsum-generator',
    category: 'generators',
    description: 'Generate placeholder text by paragraphs, sentences, or words for UI wireframes.',
    shortDescription: 'Generate placeholder text for design.',
    icon: 'FileText',
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text generator'],
    primaryKeyword: 'Lorem Ipsum Generator',
    relatedKeywords: ['dummy text generator', 'lorem ipsum text'],
    status: 'active',
    processingMode: 'client',
    component: 'LoremIpsumGenerator',
    seoTitle: 'Lorem Ipsum Generator Online | HMDevTools',
    seoDescription: 'Generate standard pseudo-Latin placeholder paragraphs, sentences, or words for layout designs.',
    howItWorks: 'Select count and output type (paragraphs, sentences, or words) to produce placeholder text.',
    features: ['Generates paragraphs, sentences, or words', 'Instant copy button'],
    useCases: ['Filling mockup layouts with realistic text length', 'Testing UI text overflow'],
    examples: [{ title: 'Sample Paragraph', output: 'Lorem ipsum dolor sit amet...' }],
    faq: [{ question: 'What is Lorem Ipsum?', answer: 'Standard placeholder text derived from Latin literature used in typography.' }],
    relatedTools: ['word-counter', 'case-converter', 'markdown-to-html']
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: 'hash-generator',
    category: 'generators',
    description: 'Generate SHA-256 and SHA-512 cryptographic hashes using the Web Crypto API, plus legacy MD5 checksums.',
    shortDescription: 'Generate SHA-256, SHA-512, and MD5 hashes.',
    icon: 'Key',
    keywords: ['hash generator', 'sha256 generator', 'md5 hash', 'crypto hash online'],
    primaryKeyword: 'Cryptographic Hash Generator',
    relatedKeywords: ['generate SHA-256 hash', 'SHA-512 hash generator', 'MD5 checksum online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'HashGenerator',
    seoTitle: 'Cryptographic Hash Generator (SHA-256, SHA-512, MD5) | HMDevTools',
    seoDescription: 'Generate SHA-256, SHA-512, and MD5 hashes locally using the native Web Crypto API.',
    howItWorks: 'Enter text to calculate SHA-256, SHA-512, and MD5 hashes in lowercase or uppercase hex.',
    features: ['Web Crypto API for SHA-256 and SHA-512', 'Legacy MD5 checksum calculation', 'Uppercase hex toggle'],
    useCases: ['Generating checksums for file integrity verification', 'Creating SHA-256 digest values for API signatures'],
    examples: [{ title: 'SHA-256 Digest', input: 'HMDevTools 2026' }],
    faq: [{ question: 'Is MD5 secure?', answer: 'No, MD5 is legacy and non-cryptographic. Use SHA-256 for security.' }],
    relatedTools: ['password-generator', 'uuid-generator', 'base64-encoder']
  },

  // -------------------------------------------------------------
  // WEB & FORMATTING (8 Active)
  // -------------------------------------------------------------
  {
    id: 'url-parser',
    name: 'URL Parser',
    slug: 'url-parser',
    category: 'web-dev',
    description: 'Break down complex URLs into protocol, domain, port, pathname, query params table, and hash fragment.',
    shortDescription: 'Parse and inspect URL components & parameters.',
    icon: 'Compass',
    keywords: ['url parser', 'parse url', 'query params parser'],
    primaryKeyword: 'URL Parser',
    relatedKeywords: ['parse URL query parameters', 'URL inspector online'],
    status: 'active',
    processingMode: 'client',
    component: 'UrlParser',
    seoTitle: 'URL Parser & Query Parameter Inspector | HMDevTools',
    seoDescription: 'Parse any web URL into hostname, path, port, scheme, and structured query key-value parameters.',
    howItWorks: 'Paste a web URL to extract and display all structural parts and query parameters.',
    features: ['Extracts scheme, hostname, port, pathname', 'Key-value query table'],
    useCases: ['Inspecting campaign tracking parameters (UTM tags)', 'Debugging query strings'],
    examples: [{ title: 'Parsed Query', input: 'https://example.com/search?q=devtools&page=2' }],
    faq: [{ question: 'Must URL include protocol?', answer: 'Yes, absolute URLs (http:// or https://) ensure correct parsing.' }],
    relatedTools: ['url-encoder', 'url-decoder', 'json-formatter']
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    slug: 'html-formatter',
    category: 'web-dev',
    description: 'Beautify HTML markup with clean indentation, proper tag nesting, and line breaks.',
    shortDescription: 'Format and beautify HTML markup.',
    icon: 'Code',
    keywords: ['html formatter', 'beautify html', 'format html'],
    primaryKeyword: 'HTML Formatter',
    relatedKeywords: ['beautify HTML markup', 'format HTML online'],
    status: 'active',
    processingMode: 'client',
    component: 'HtmlFormatter',
    seoTitle: 'HTML Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format raw unindented HTML tags with clean indentation locally in your web browser.',
    howItWorks: 'Paste raw or minified HTML to auto-format nested elements with clean spacing.',
    features: ['Clean 2-space tag indentation', 'Preserves element nesting structure'],
    useCases: ['Beautifying minified HTML template strings', 'Cleaning inline HTML code'],
    examples: [{ title: 'HTML Formatting', input: '<div><p>Hello</p></div>' }],
    faq: [{ question: 'Does it support self-closing tags?', answer: 'Yes, tags like <img> and <br> are handled without corrupting nesting.' }],
    relatedTools: ['css-formatter', 'js-formatter', 'markdown-to-html']
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    slug: 'css-formatter',
    category: 'web-dev',
    description: 'Beautify messy CSS stylesheets with consistent selector spacing, indentation, and declaration rules.',
    shortDescription: 'Format and beautify CSS stylesheets.',
    icon: 'Palette',
    keywords: ['css formatter', 'beautify css', 'format css'],
    primaryKeyword: 'CSS Formatter',
    relatedKeywords: ['beautify CSS styles', 'format CSS online'],
    status: 'active',
    processingMode: 'client',
    component: 'CssFormatter',
    seoTitle: 'CSS Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Beautify CSS stylesheets and rulesets with clean formatting and selector indentation.',
    howItWorks: 'Paste messy CSS rules to re-format declarations with consistent indentation.',
    features: ['Formats selectors and CSS declarations', 'Clean multi-line rulesets'],
    useCases: ['Formatting compressed CSS rulesets', 'Standardizing CSS code style'],
    examples: [{ title: 'CSS Format', input: 'body{margin:0;padding:0}' }],
    faq: [{ question: 'Does it support media queries?', answer: 'Yes, nested media query blocks are formatted with clean indentation.' }],
    relatedTools: ['css-minifier', 'html-formatter', 'js-formatter']
  },
  {
    id: 'js-formatter',
    name: 'JavaScript Formatter',
    slug: 'js-formatter',
    category: 'web-dev',
    description: 'Beautify JavaScript/ECMAScript code with configurable indentation and syntax formatting.',
    shortDescription: 'Beautify JavaScript and ES6 code.',
    icon: 'FileCode2',
    keywords: ['js formatter', 'javascript beautifier', 'format javascript'],
    primaryKeyword: 'JavaScript Formatter',
    relatedKeywords: ['beautify JavaScript online', 'format JS code'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsFormatter',
    seoTitle: 'JavaScript Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format and prettify JavaScript code strings directly in your browser memory.',
    howItWorks: 'Paste JavaScript code to produce clean, readable formatted scripts.',
    features: ['Formats ES6+ JavaScript syntax', 'Cleans statement indentation'],
    useCases: ['De-obfuscating single-line JS snippets', 'Formatting inline event handler code'],
    examples: [{ title: 'JS Format', input: 'function test(){return true;}' }],
    faq: [{ question: 'Does formatting execute your JavaScript?', answer: 'No. Formatting is purely static text parsing.' }],
    relatedTools: ['js-minifier', 'html-formatter', 'css-formatter']
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    slug: 'markdown-to-html',
    category: 'web-dev',
    description: 'Convert Markdown text syntax into clean, sanitized HTML markup for web publishing.',
    shortDescription: 'Convert Markdown into sanitized HTML.',
    icon: 'FileText',
    keywords: ['markdown to html', 'convert markdown', 'md to html', 'markdown parser'],
    primaryKeyword: 'Markdown to HTML',
    relatedKeywords: ['convert Markdown to HTML online', 'Markdown parser with XSS protection'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'MarkdownToHtml',
    seoTitle: 'Markdown to HTML Converter Online | HMDevTools',
    seoDescription: 'Convert Markdown text into sanitized HTML markup locally with XSS security protection.',
    howItWorks: 'Paste Markdown content to render sanitized HTML markup with heading tags, lists, and links.',
    features: ['Parses headings (#, ##), bold, italic, lists, and links', 'XSS sanitization stripping script tags', 'Instant client-side parsing'],
    useCases: ['Converting README files for web publishing', 'Generating HTML from blog post markdown drafts'],
    examples: [{ title: 'Markdown to HTML', input: '# Title\n- Item 1\n- Item 2', output: '<h1>Title</h1>\n<ul><li>Item 1</li><li>Item 2</li></ul>' }],
    faq: [{ question: 'Is the output sanitized against XSS?', answer: 'Yes, executable script tags and inline event attributes are stripped.' }],
    relatedTools: ['html-to-markdown', 'html-formatter', 'lorem-ipsum-generator']
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    slug: 'html-to-markdown',
    category: 'web-dev',
    description: 'Convert raw HTML elements and markup back into clean Markdown syntax.',
    shortDescription: 'Convert HTML tags into Markdown syntax.',
    icon: 'FileCode',
    keywords: ['html to markdown', 'convert html to md', 'html markdown converter'],
    primaryKeyword: 'HTML to Markdown',
    relatedKeywords: ['convert HTML to Markdown online', 'HTML to MD converter'],
    status: 'active',
    processingMode: 'client',
    isPopular: false,
    isNew: true,
    component: 'HtmlToMarkdown',
    seoTitle: 'HTML to Markdown Converter Online | HMDevTools',
    seoDescription: 'Convert HTML markup into clean Markdown text syntax in your browser.',
    howItWorks: 'Paste HTML elements to transform tags into equivalent Markdown headers, lists, and links.',
    features: ['Converts <h1>-<h6>, <p>, <a>, <ul>, <li>, and <code> tags', 'Clean text formatting'],
    useCases: ['Converting web page HTML into Markdown documentation', 'Migrating HTML content to static site generators'],
    examples: [{ title: 'HTML to MD', input: '<h2>Header</h2><p>Text</p>', output: '## Header\n\nText' }],
    faq: [{ question: 'Does it handle nested elements?', answer: 'Yes, nested list items and formatted inline text are preserved.' }],
    relatedTools: ['markdown-to-html', 'html-decoder', 'html-formatter']
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    slug: 'css-minifier',
    category: 'web-dev',
    description: 'Minify and compress CSS stylesheets by removing whitespace and comments without corrupting styles.',
    shortDescription: 'Compress and minify CSS stylesheets.',
    icon: 'Minimize2',
    keywords: ['css minifier', 'minify css', 'compress css stylesheet'],
    primaryKeyword: 'CSS Minifier',
    relatedKeywords: ['compress CSS online', 'minify CSS code', 'CSS bandwidth optimizer'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'CssMinifier',
    seoTitle: 'CSS Minifier & Compressor Online | HMDevTools',
    seoDescription: 'Minify CSS stylesheets by stripping unneeded comments and whitespace to optimize file size.',
    howItWorks: 'Paste CSS rules to calculate minified stylesheet output and savings percentage.',
    features: ['Strips comments and whitespace', 'Calculates size reduction savings %', 'Preserves selectors and media queries'],
    useCases: ['Optimizing CSS stylesheets for production web deployment', 'Reducing bandwidth transfer size'],
    examples: [{ title: 'CSS Minification', input: 'body {\n  margin: 0;\n}', output: 'body{margin:0}' }],
    faq: [{ question: 'Does minifying alter CSS selectors?', answer: 'No, minifying only removes non-semantic whitespace and comments.' }],
    relatedTools: ['css-formatter', 'js-minifier', 'html-formatter']
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    slug: 'js-minifier',
    category: 'web-dev',
    description: 'Compress and minify JavaScript code strings safely by stripping comments and unneeded line breaks.',
    shortDescription: 'Compress and minify JavaScript code.',
    icon: 'Minimize2',
    keywords: ['js minifier', 'javascript minifier', 'compress js code'],
    primaryKeyword: 'JavaScript Minifier',
    relatedKeywords: ['compress JavaScript online', 'minify JS script', 'JS code compressor'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'JsMinifier',
    seoTitle: 'JavaScript Minifier & Compressor Online | HMDevTools',
    seoDescription: 'Compress JavaScript code by removing unneeded comments and line breaks safely in your browser.',
    howItWorks: 'Paste JavaScript code to produce minified single-line or compressed script outputs.',
    features: ['Safely strips single-line and block comments', 'Calculates file size savings %', '100% browser-local'],
    useCases: ['Minifying small JS utility scripts for production', 'Reducing payload size for inline script tags'],
    examples: [{ title: 'JS Minification', input: '// Comment\nfunction add(a, b) {\n  return a + b;\n}', output: 'function add(a,b){return a+b;}' }],
    faq: [{ question: 'Is my JS code executed during minification?', answer: 'Never. Code is processed purely as text parsing.' }],
    relatedTools: ['js-formatter', 'css-minifier', 'html-formatter']
  },

  // -------------------------------------------------------------
  // DATES & TIME (4 Active)
  // -------------------------------------------------------------
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    slug: 'unix-timestamp-converter',
    category: 'dates-time',
    description: 'Convert Unix epoch timestamps (seconds or milliseconds) to ISO dates, UTC, and local time.',
    shortDescription: 'Convert between Unix timestamps and human dates.',
    icon: 'Clock',
    keywords: ['unix timestamp converter', 'epoch converter', 'timestamp to date'],
    primaryKeyword: 'Unix Timestamp Converter',
    relatedKeywords: ['convert epoch timestamp', 'timestamp to ISO date'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'UnixTimestampConverter',
    seoTitle: 'Unix Timestamp / Epoch Converter Online | HMDevTools',
    seoDescription: 'Convert seconds and milliseconds epoch timestamps to human-readable ISO and UTC dates.',
    howItWorks: 'Enter a numeric timestamp to calculate ISO 8601, UTC, and local calendar dates.',
    features: ['Auto-detects 10-digit seconds vs 13-digit milliseconds', 'Outputs UTC and ISO strings'],
    useCases: ['Debugging database timestamp integers', 'Converting API epoch values'],
    examples: [{ title: 'Epoch to Date', input: '1700000000', output: '2023-11-14T22:13:20.000Z' }],
    faq: [{ question: 'What is Unix epoch time?', answer: 'Number of seconds elapsed since January 1, 1970 00:00:00 UTC.' }],
    relatedTools: ['timestamp-to-date', 'date-to-timestamp', 'cron-expression-helper']
  },
  {
    id: 'timestamp-to-date',
    name: 'Timestamp to Date',
    slug: 'timestamp-to-date',
    category: 'dates-time',
    description: 'Convert numeric Unix epoch timestamps directly into human-readable date formats across timezones.',
    shortDescription: 'Convert Unix epoch numbers to readable dates.',
    icon: 'Calendar',
    keywords: ['timestamp to date', 'epoch to date'],
    primaryKeyword: 'Timestamp to Date',
    relatedKeywords: ['epoch to human date', 'convert Unix timestamp to date'],
    status: 'active',
    processingMode: 'client',
    component: 'TimestampToDate',
    seoTitle: 'Timestamp to Date Converter Online | HMDevTools',
    seoDescription: 'Convert Unix timestamps into readable local and UTC date strings in your browser.',
    howItWorks: 'Paste a numeric timestamp integer to calculate exact calendar date and time.',
    features: ['Supports seconds and milliseconds', 'Displays UTC and local time string outputs'],
    useCases: ['Converting server log timestamps to readable dates'],
    examples: [{ title: 'Sample Epoch', input: '1609459200', output: '2021-01-01 00:00:00 UTC' }],
    faq: [{ question: 'Does it support negative timestamps?', answer: 'Yes, negative timestamps represent dates prior to Jan 1, 1970.' }],
    relatedTools: ['unix-timestamp-converter', 'date-to-timestamp']
  },
  {
    id: 'date-to-timestamp',
    name: 'Date to Timestamp',
    slug: 'date-to-timestamp',
    category: 'dates-time',
    description: 'Pick or enter calendar dates to generate exact Unix epoch timestamp numbers in seconds and milliseconds.',
    shortDescription: 'Convert calendar date/time into epoch timestamps.',
    icon: 'CalendarCheck',
    keywords: ['date to timestamp', 'date to epoch'],
    primaryKeyword: 'Date to Timestamp',
    relatedKeywords: ['convert date to Unix epoch', 'generate epoch timestamp'],
    status: 'active',
    processingMode: 'client',
    component: 'DateToTimestamp',
    seoTitle: 'Date to Unix Timestamp Converter Online | HMDevTools',
    seoDescription: 'Convert any calendar date and time into Unix epoch seconds and milliseconds.',
    howItWorks: 'Select a date and time using the picker to generate exact Unix epoch integers.',
    features: ['Interactive date picker input', 'Calculates both seconds and milliseconds'],
    useCases: ['Generating database query timestamp boundaries'],
    examples: [{ title: 'Date Input', input: '2026-01-01T00:00:00Z', output: '1767225600' }],
    faq: [{ question: 'Is UTC or local time used?', answer: 'Outputs both UTC ISO strings and Unix seconds.' }],
    relatedTools: ['unix-timestamp-converter', 'timestamp-to-date']
  },
  {
    id: 'cron-expression-helper',
    name: 'Cron Expression Helper',
    slug: 'cron-expression-helper',
    category: 'dates-time',
    description: 'Build, validate, and explain 5-field cron schedule expressions with plain English descriptions and preset shortcuts.',
    shortDescription: 'Build and explain cron schedule expressions.',
    icon: 'Clock',
    keywords: ['cron expression helper', 'cron builder', 'cron explainer', 'cron schedule parser'],
    primaryKeyword: 'Cron Expression Helper',
    relatedKeywords: ['explain cron expression', 'cron schedule builder online', 'cron syntax explainer'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'CronExpressionHelper',
    seoTitle: 'Cron Expression Helper & Explainer | HMDevTools',
    seoDescription: 'Build, validate, and parse standard 5-field cron schedule expressions into natural English explanations.',
    howItWorks: 'Enter a 5-field cron expression or select a schedule preset to view field breakdowns and plain English descriptions.',
    features: ['Natural language schedule explanation', 'Field-by-field breakdown (minute, hour, day, month, day of week)', 'Preset buttons for common schedules'],
    useCases: ['Configuring backend cron jobs and scheduled tasks', 'Understanding legacy cron expressions in crontabs'],
    examples: [{ title: 'Every 15 Minutes', input: '*/15 * * * *', output: 'Runs every 15 minutes.' }],
    faq: [{ question: 'Which cron dialect is explained?', answer: 'Standard 5-field crontab format (minute, hour, day of month, month, day of week).' }],
    relatedTools: ['unix-timestamp-converter', 'timestamp-to-date']
  },

  // -------------------------------------------------------------
  // REGEX (1 Active)
  // -------------------------------------------------------------
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    slug: 'regex-tester',
    category: 'regex',
    description: 'Test and debug JavaScript regular expressions with real-time match highlighting, regex flags, and capture groups.',
    shortDescription: 'Test regular expressions with instant match highlighting.',
    icon: 'Regex',
    keywords: ['regex tester', 'regular expression tester', 'test regex online'],
    primaryKeyword: 'Regex Tester',
    relatedKeywords: ['regular expression matcher', 'test JS regex'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'RegexTester',
    seoTitle: 'Regex Tester & Matcher Online | HMDevTools',
    seoDescription: 'Test JavaScript regular expressions with real-time match highlighting, regex flags, and capture group diagnostics.',
    howItWorks: 'Enter your regular expression pattern, select flags (g, i, m), and paste a test string.',
    features: ['Supports flags (g, i, m)', 'Displays match count and index position', 'Length guards'],
    useCases: ['Testing email and phone number validation patterns'],
    examples: [{ title: 'Email Matcher', input: '[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}' }],
    faq: [{ question: 'Which regex engine is used?', answer: 'Native V8 JavaScript RegExp engine.' }],
    relatedTools: ['text-diff', 'word-counter', 'case-converter']
  },

  // -------------------------------------------------------------
  // SQL & DATABASES (1 Active)
  // -------------------------------------------------------------
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    slug: 'sql-formatter',
    category: 'sql-databases',
    description: 'Format and beautify complex SQL queries (SELECT, INSERT, UPDATE, JOINs) with standardized keyword capitalization.',
    shortDescription: 'Format and beautify SQL queries.',
    icon: 'Database',
    keywords: ['sql formatter', 'beautify sql', 'format sql query'],
    primaryKeyword: 'SQL Formatter',
    relatedKeywords: ['beautify SQL query', 'format SQL online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'SqlFormatter',
    seoTitle: 'SQL Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format SQL queries with clean keyword capitalization and statement indentation in your browser.',
    howItWorks: 'Paste raw or single-line SQL queries to format keywords (SELECT, FROM, WHERE, JOIN).',
    features: ['Capitalizes standard SQL keywords', 'Formats SELECT, JOIN, and WHERE clauses'],
    useCases: ['Formatting database query logs for inspection'],
    examples: [{ title: 'Raw SELECT Query', input: 'select u.id from users u where u.status="active"' }],
    faq: [{ question: 'Which SQL dialects are supported?', answer: 'ANSI SQL, MySQL, PostgreSQL, SQLite, and SQL Server.' }],
    relatedTools: ['json-formatter', 'text-diff', 'case-converter']
  },

  // -------------------------------------------------------------
  // TEXT UTILITIES (4 Active)
  // -------------------------------------------------------------
  {
    id: 'word-counter',
    name: 'Word Counter',
    slug: 'word-counter',
    category: 'text-utilities',
    description: 'Count words, characters (with and without spaces), sentences, paragraphs, and estimated reading time.',
    shortDescription: 'Count words, characters, and reading time.',
    icon: 'AlignLeft',
    keywords: ['word counter', 'character counter', 'count words'],
    primaryKeyword: 'Word Counter',
    relatedKeywords: ['count words online', 'character counter with spaces'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'WordCounter',
    seoTitle: 'Word & Character Counter Online | HMDevTools',
    seoDescription: 'Count words, characters (with & without spaces), lines, and reading duration in real-time.',
    howItWorks: 'Type or paste text into the input panel to see live word and character count stats.',
    features: ['Live real-time word and character count', 'Calculates estimated reading duration'],
    useCases: ['Verifying blog post word counts', 'Checking meta description character limits'],
    examples: [{ title: 'Sample Text Stats', input: 'HMDevTools provides 50 developer utilities.' }],
    faq: [{ question: 'How is reading time calculated?', answer: 'Assuming average reading speed of 200 words per minute.' }],
    relatedTools: ['case-converter', 'remove-duplicate-lines', 'lorem-ipsum-generator']
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    slug: 'case-converter',
    category: 'text-utilities',
    description: 'Transform text case between UPPERCASE, lowercase, camelCase, PascalCase, snake_case, kebab-case, and Title Case.',
    shortDescription: 'Convert text case (camelCase, snake_case, etc.).',
    icon: 'Type',
    keywords: ['case converter', 'camelcase converter', 'snake_case', 'kebab-case'],
    primaryKeyword: 'Case Converter',
    relatedKeywords: ['convert string case', 'camelCase generator'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'CaseConverter',
    seoTitle: 'Text Case Converter (camelCase, snake_case) | HMDevTools',
    seoDescription: 'Convert text between programming variable styles (camelCase, snake_case, kebab-case, PascalCase) and text cases.',
    howItWorks: 'Paste text or variable names and select your target case format button.',
    features: ['Supports camelCase, PascalCase, snake_case, kebab-case, UPPERCASE, lowercase'],
    useCases: ['Converting database column names to camelCase JS properties'],
    examples: [{ title: 'camelCase Conversion', input: 'hello world', output: 'helloWorld' }],
    faq: [{ question: 'Does it support multi-word strings?', answer: 'Yes, delimiters are handled correctly.' }],
    relatedTools: ['word-counter', 'remove-duplicate-lines', 'html-formatter']
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    slug: 'remove-duplicate-lines',
    category: 'text-utilities',
    description: 'Deduplicate text lists by removing repeated identical lines, with optional case sensitivity.',
    shortDescription: 'Remove duplicate lines from text lists.',
    icon: 'ListFilter',
    keywords: ['remove duplicate lines', 'deduplicate list', 'unique lines'],
    primaryKeyword: 'Remove Duplicate Lines',
    relatedKeywords: ['deduplicate text list', 'filter unique lines'],
    status: 'active',
    processingMode: 'client',
    component: 'RemoveDuplicateLines',
    seoTitle: 'Remove Duplicate Lines Online | HMDevTools',
    seoDescription: 'Deduplicate text lists and filter unique lines instantly in your web browser.',
    howItWorks: 'Paste a list of text lines into the input area to filter duplicate entries.',
    features: ['Instant deduplication', 'Case-sensitive toggle', 'Preserves list ordering'],
    useCases: ['Deduplicating lists of URLs or email addresses'],
    examples: [{ title: 'Deduplicate List', input: 'apple\nbanana\napple', output: 'apple\nbanana' }],
    faq: [{ question: 'Does it preserve original line order?', answer: 'Yes, first occurrence of each line is kept.' }],
    relatedTools: ['word-counter', 'text-diff', 'case-converter']
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    slug: 'text-diff',
    category: 'text-utilities',
    description: 'Compare two text strings or code files side-by-side to highlight added, removed, and modified lines.',
    shortDescription: 'Compare two text snippets for differences.',
    icon: 'GitCompare',
    keywords: ['text diff', 'compare text', 'diff checker'],
    primaryKeyword: 'Text Diff',
    relatedKeywords: ['compare text online', 'diff checker tool'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'TextDiff',
    seoTitle: 'Text Diff & Code Comparator Online | HMDevTools',
    seoDescription: 'Compare two text blocks or code files side-by-side with line difference highlights in your browser.',
    howItWorks: 'Paste original text in left panel and modified text in right panel.',
    features: ['Line-by-line diff comparison', 'Color-coded addition (+)/removal (-) highlights'],
    useCases: ['Comparing two versions of a code snippet'],
    examples: [{ title: 'Text Difference', input: 'Left vs Right text blocks' }],
    faq: [{ question: 'Are files sent to a server?', answer: 'No, comparison logic runs 100% locally.' }],
    relatedTools: ['word-counter', 'remove-duplicate-lines', 'regex-tester']
  },

  // -------------------------------------------------------------
  // CODE CONVERSION (5 Active)
  // -------------------------------------------------------------
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    slug: 'json-to-typescript',
    category: 'code-conversion',
    description: 'Convert JSON object samples into strongly typed TypeScript interface or type definitions.',
    shortDescription: 'Convert JSON payload to TypeScript interfaces.',
    icon: 'FileCode',
    keywords: ['json to typescript', 'json to ts', 'generate typescript interface'],
    primaryKeyword: 'JSON to TypeScript',
    relatedKeywords: ['convert JSON to TS interface', 'generate TypeScript types'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonToTypescript',
    seoTitle: 'JSON to TypeScript Interface Converter | HMDevTools',
    seoDescription: 'Generate clean TypeScript interface and type definitions from JSON object payloads locally.',
    howItWorks: 'Paste a JSON payload to automatically derive TypeScript interface definitions.',
    features: ['Generates TypeScript interface syntax', 'Maps numbers, strings, booleans, arrays, objects'],
    useCases: ['Generating TypeScript interfaces for REST API responses'],
    examples: [{ title: 'Generate Interface', input: '{"id":1,"user":"dev"}', output: 'export interface RootObject {\n  id: number;\n  user: string;\n}' }],
    faq: [{ question: 'Does it support nested JSON objects?', answer: 'Yes, generates typed properties for nested structures.' }],
    relatedTools: ['json-to-python', 'json-to-go', 'json-to-java', 'json-to-csharp']
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    slug: 'json-to-python',
    category: 'code-conversion',
    description: 'Convert JSON objects into Python dictionary or Dataclass models.',
    shortDescription: 'Convert JSON objects into Python Dataclasses.',
    icon: 'Code2',
    keywords: ['json to python', 'json to dataclass', 'python dataclass generator'],
    primaryKeyword: 'JSON to Python',
    relatedKeywords: ['convert JSON to Python Dataclass', 'generate Python class'],
    status: 'active',
    processingMode: 'client',
    isNew: true,
    component: 'JsonToPython',
    seoTitle: 'JSON to Python Dataclass Converter | HMDevTools',
    seoDescription: 'Convert JSON payloads into Python 3 Dataclass models and type-annotated code in your browser.',
    howItWorks: 'Paste JSON content to produce Python 3 @dataclass classes with typing annotations.',
    features: ['Generates Python 3.7+ @dataclass syntax', 'Maps int, float, str, bool, List'],
    useCases: ['Creating Python data models for FastAPI or Django backends'],
    examples: [{ title: 'Python Dataclass', input: '{"name":"item","price":19.99}' }],
    faq: [{ question: 'Which Python version is supported?', answer: 'Standard Python 3.7+ dataclass syntax.' }],
    relatedTools: ['json-to-typescript', 'json-to-go', 'json-to-java']
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go',
    slug: 'json-to-go',
    category: 'code-conversion',
    description: 'Convert JSON payloads into Golang struct definitions with json field tags.',
    shortDescription: 'Convert JSON payloads into Go struct definitions.',
    icon: 'Cpu',
    keywords: ['json to go', 'json to golang struct', 'go struct generator'],
    primaryKeyword: 'JSON to Go',
    relatedKeywords: ['convert JSON to Go struct', 'generate Go struct'],
    status: 'active',
    processingMode: 'client',
    isNew: true,
    component: 'JsonToGo',
    seoTitle: 'JSON to Go Struct Generator | HMDevTools',
    seoDescription: 'Convert JSON objects into idiomatic Go struct types with json struct field tags.',
    howItWorks: 'Paste a JSON sample payload to output Golang struct type definitions.',
    features: ['Generates idiomatic Go struct types', 'Includes json field tags'],
    useCases: ['Generating Go structs for API unmarshaling (json.Unmarshal)'],
    examples: [{ title: 'Go Struct', input: '{"user_id":42}' }],
    faq: [{ question: 'Are json field tags included?', answer: 'Yes, fields include standard `json:"key"` tags.' }],
    relatedTools: ['json-to-typescript', 'json-to-python', 'json-to-csharp']
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java (POJO)',
    slug: 'json-to-java',
    category: 'code-conversion',
    description: 'Convert JSON payload samples into clean Java POJO class definitions with getters and setters.',
    shortDescription: 'Convert JSON to Java POJO classes.',
    icon: 'Code',
    keywords: ['json to java', 'json to pojo', 'java class generator from json'],
    primaryKeyword: 'JSON to Java',
    relatedKeywords: ['convert JSON to Java POJO class', 'generate Java class from JSON'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'JsonToJava',
    seoTitle: 'JSON to Java POJO Class Converter | HMDevTools',
    seoDescription: 'Convert JSON objects and arrays into Java POJO class models with private fields and getter/setter methods.',
    howItWorks: 'Paste a JSON payload and set your root Java class name to generate valid Java POJO code.',
    features: ['Generates Java classes with private fields and getters/setters', 'Handles primitive types and java.util.List', 'Client-side generation'],
    useCases: ['Creating Java DTO class models for Spring Boot backends', 'Parsing REST API payloads into Java objects'],
    examples: [{ title: 'Java POJO', input: '{"id":101,"name":"Dev"}', output: 'public class RootResponse {\n    private Integer id;\n    private String name;\n}' }],
    faq: [{ question: 'Does it generate getters and setters?', answer: 'Yes, standard public getField() and setField() methods are generated.' }],
    relatedTools: ['json-to-csharp', 'json-to-typescript', 'json-to-python']
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C# (POCO)',
    slug: 'json-to-csharp',
    category: 'code-conversion',
    description: 'Convert JSON objects into C# POCO class definitions with System.Text.Json JsonPropertyName attributes.',
    shortDescription: 'Convert JSON to C# POCO classes.',
    icon: 'Code2',
    keywords: ['json to c#', 'json to csharp', 'csharp class generator from json'],
    primaryKeyword: 'JSON to C#',
    relatedKeywords: ['convert JSON to C# class', 'generate C# POCO from JSON'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    isNew: true,
    component: 'JsonToCsharp',
    seoTitle: 'JSON to C# POCO Class Converter | HMDevTools',
    seoDescription: 'Convert JSON payloads into idiomatic C# POCO classes with JsonPropertyName attributes locally in your browser.',
    howItWorks: 'Paste JSON content to produce C# class properties with System.Text.Json attributes.',
    features: ['Generates C# auto-properties { get; set; }', 'Includes [JsonPropertyName("key")] attributes', 'Maps List<T> collections'],
    useCases: ['Creating C# DTO models for ASP.NET Core Web APIs', 'Unmarshaling JSON config files in C#'],
    examples: [{ title: 'C# POCO Class', input: '{"user_id":42}', output: 'public class RootObject {\n    [JsonPropertyName("user_id")]\n    public int UserId { get; set; }\n}' }],
    faq: [{ question: 'Which JSON serializer attribute is used?', answer: 'Uses standard System.Text.Json.Serialization.JsonPropertyName.' }],
    relatedTools: ['json-to-java', 'json-to-typescript', 'json-to-go']
  },

  // -------------------------------------------------------------
  // REMAINING STAGED COMING-SOON TOOLS (4 Staged)
  // -------------------------------------------------------------
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    slug: 'timezone-converter',
    category: 'dates-time',
    description: 'Convert date and time values across global timezones.',
    shortDescription: 'Convert dates across global timezones.',
    icon: 'Globe',
    keywords: ['timezone converter', 'utc to est'],
    primaryKeyword: 'Timezone Converter',
    relatedKeywords: ['convert timezones'],
    status: 'coming-soon',
    processingMode: 'client',
    component: 'GenericToolFallback',
    seoTitle: 'Timezone Converter — HMDevTools',
    seoDescription: 'Convert dates across timezones.'
  },
  {
    id: 'regex-explainer',
    name: 'Regex Explainer',
    slug: 'regex-explainer',
    category: 'regex',
    description: 'Break down complex regex patterns into plain English.',
    shortDescription: 'Explain regex patterns in plain English.',
    icon: 'HelpCircle',
    keywords: ['regex explainer', 'regex breakdown'],
    primaryKeyword: 'Regex Explainer',
    relatedKeywords: ['explain regex'],
    status: 'coming-soon',
    processingMode: 'client',
    component: 'GenericToolFallback',
    seoTitle: 'Regex Explainer — HMDevTools',
    seoDescription: 'Explain regex in plain English.'
  },
  {
    id: 'sql-minifier',
    name: 'SQL Minifier',
    slug: 'sql-minifier',
    category: 'sql-databases',
    description: 'Compress SQL statements to single-line string queries.',
    shortDescription: 'Minify SQL queries to single line.',
    icon: 'Minimize2',
    keywords: ['sql minifier', 'compress sql'],
    primaryKeyword: 'SQL Minifier',
    relatedKeywords: ['compress SQL statement'],
    status: 'coming-soon',
    processingMode: 'client',
    component: 'GenericToolFallback',
    seoTitle: 'SQL Minifier — HMDevTools',
    seoDescription: 'Minify SQL queries.'
  },
  {
    id: 'whitespace-cleaner',
    name: 'Whitespace Cleaner',
    slug: 'whitespace-cleaner',
    category: 'text-utilities',
    description: 'Strip leading, trailing, and duplicate spaces from text.',
    shortDescription: 'Clean extra whitespace from text.',
    icon: 'ListFilter',
    keywords: ['whitespace cleaner', 'trim spaces'],
    primaryKeyword: 'Whitespace Cleaner',
    relatedKeywords: ['strip extra spaces'],
    status: 'coming-soon',
    processingMode: 'client',
    component: 'GenericToolFallback',
    seoTitle: 'Whitespace Cleaner — HMDevTools',
    seoDescription: 'Clean extra spaces from text.'
  }
];

export const getToolBySlug = (slug) => {
  return toolsRegistry.find(t => t.slug === slug || t.id === slug);
};

export const getToolsByCategory = (categorySlug) => {
  return toolsRegistry.filter(t => t.category === categorySlug);
};

export const getPopularTools = () => {
  return toolsRegistry.filter(t => t.isPopular);
};

export const getNewTools = () => {
  return toolsRegistry.filter(t => t.isNew);
};
