export const toolsRegistry = [
  // -------------------------------------------------------------
  // JSON & DATA (11 Active)
  // -------------------------------------------------------------
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    category: 'json-data',
    description: 'Format, beautify, and inspect raw JSON data with customizable indentation and instant syntax error detection.',
    shortDescription: 'Format and beautify raw JSON data.',
    icon: 'FileJson',
    keywords: ['json formatter', 'json beautifier', 'format json'],
    primaryKeyword: 'JSON Formatter',
    relatedKeywords: ['JSON beautifier', 'format JSON online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonFormatter',
    seoTitle: 'JSON Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format, beautify, and parse raw JSON strings instantly in your web browser with local privacy processing.',
    howItWorks: 'Paste your JSON string into the editor and click Format JSON.',
    features: ['Configurable indentation', 'Real-time syntax validation', '100% browser-local'],
    useCases: ['Formatting minified API responses', 'Inspecting package.json config files'],
    examples: [{ title: 'Beautify JSON', input: '{"service":"HMDevTools"}', output: '{\n  "service": "HMDevTools"\n}' }],
    faq: [{ question: 'Is my JSON transmitted to a server?', answer: 'No, formatting runs 100% locally in browser JS.' }],
    relatedTools: ['json-validator', 'json-minifier', 'json-viewer', 'json-to-xml']
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    slug: 'json-validator',
    category: 'json-data',
    description: 'Validate JSON syntax compliance against RFC 8259 specifications with exact error locations.',
    shortDescription: 'Validate JSON syntax and RFC 8259 compliance.',
    icon: 'CheckCircle2',
    keywords: ['json validator', 'validate json'],
    primaryKeyword: 'JSON Validator',
    relatedKeywords: ['validate JSON online', 'JSON syntax checker'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonValidator',
    seoTitle: 'JSON Validator & Syntax Checker Online | HMDevTools',
    seoDescription: 'Validate your JSON strings against official RFC 8259 specifications with instant syntax diagnostics.',
    howItWorks: 'Paste your JSON data into the editor to check quote placement and data types.',
    features: ['Instant validation status', 'Detailed error reporting'],
    useCases: ['Verifying webhook payloads before testing'],
    examples: [{ title: 'Valid RFC 8259 JSON', input: '{"status": "ok"}' }],
    faq: [{ question: 'What JSON standards are validated?', answer: 'Strict RFC 8259 rules.' }],
    relatedTools: ['json-formatter', 'json-minifier']
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    slug: 'json-minifier',
    category: 'json-data',
    description: 'Compress and minify raw JSON by stripping whitespace and newlines for minimal payload transfer size.',
    shortDescription: 'Minify and compress JSON strings.',
    icon: 'Minimize2',
    keywords: ['json minifier', 'minify json'],
    primaryKeyword: 'JSON Minifier',
    relatedKeywords: ['compress JSON', 'strip JSON whitespace'],
    status: 'active',
    processingMode: 'client',
    component: 'JsonMinifier',
    seoTitle: 'JSON Minifier & Compressor Online | HMDevTools',
    seoDescription: 'Compress and minify JSON strings instantly in your browser to reduce network transfer size.',
    howItWorks: 'Paste formatted JSON to output a single-line minified string.',
    features: ['Strips unneeded indentation', 'Reduces HTTP payload sizes'],
    useCases: ['Minifying configuration objects'],
    examples: [{ title: 'Minify Example', input: '{\n  "foo": "bar"\n}', output: '{"foo":"bar"}' }],
    faq: [{ question: 'Does minifying alter values?', answer: 'No, only removes whitespace.' }],
    relatedTools: ['json-formatter', 'json-validator']
  },
  {
    id: 'json-viewer',
    name: 'JSON Viewer',
    slug: 'json-viewer',
    category: 'json-data',
    description: 'Interactive tree viewer to explore nested JSON objects and arrays with expand/collapse nodes.',
    shortDescription: 'Interactive tree view for nested JSON.',
    icon: 'Eye',
    keywords: ['json viewer', 'json tree view'],
    primaryKeyword: 'JSON Viewer',
    relatedKeywords: ['inspect JSON', 'collapsible JSON tree'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonViewer',
    seoTitle: 'Interactive JSON Viewer & Inspector | HMDevTools',
    seoDescription: 'Explore deep nested JSON objects and arrays with an interactive collapsible tree view.',
    howItWorks: 'Paste raw JSON to render an interactive node tree representation.',
    features: ['Collapsible nodes', 'Color-coded data types'],
    useCases: ['Exploring multi-level API responses'],
    examples: [{ title: 'Nested JSON', input: '{"user":{"id":1}}' }],
    faq: [{ question: 'Can I expand/collapse nodes?', answer: 'Yes, click node headers to toggle.' }],
    relatedTools: ['json-formatter', 'json-to-xml']
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    slug: 'json-to-csv',
    category: 'json-data',
    description: 'Convert JSON object arrays into tabular CSV format for spreadsheets and data imports.',
    shortDescription: 'Convert JSON arrays to CSV spreadsheets.',
    icon: 'FileSpreadsheet',
    keywords: ['json to csv', 'convert json to csv'],
    primaryKeyword: 'JSON to CSV',
    relatedKeywords: ['convert JSON array to CSV', 'export JSON to Excel'],
    status: 'active',
    processingMode: 'client',
    component: 'JsonToCsv',
    seoTitle: 'JSON to CSV Converter Online | HMDevTools',
    seoDescription: 'Convert JSON object arrays into clean CSV format for Excel or Google Sheets locally.',
    howItWorks: 'Paste a JSON array of objects to extract property headers and convert rows.',
    features: ['Extracts CSV header row', 'Handles quotes correctly'],
    useCases: ['Converting API datasets into CSV for Excel'],
    examples: [{ title: 'JSON Array to CSV', input: '[{"name":"Alice","age":30}]', output: 'name,age\nAlice,30' }],
    faq: [{ question: 'Handles commas in text?', answer: 'Yes, fields with commas are quoted.' }],
    relatedTools: ['csv-to-json', 'json-to-yaml']
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    slug: 'csv-to-json',
    category: 'json-data',
    description: 'Parse CSV tabular spreadsheets into structured JSON object arrays.',
    shortDescription: 'Parse CSV text into structured JSON.',
    icon: 'FileCode',
    keywords: ['csv to json', 'convert csv to json'],
    primaryKeyword: 'CSV to JSON',
    relatedKeywords: ['parse CSV string', 'convert spreadsheet to JSON'],
    status: 'active',
    processingMode: 'client',
    component: 'CsvToJson',
    seoTitle: 'CSV to JSON Converter Online | HMDevTools',
    seoDescription: 'Convert CSV tabular data into structured JSON array objects locally.',
    howItWorks: 'Paste comma-separated rows with a header row to generate JSON objects.',
    features: ['Header row parsing', 'Trims whitespace'],
    useCases: ['Converting exported spreadsheets into JSON'],
    examples: [{ title: 'CSV to JSON', input: 'id,name\n101,Dev', output: '[\n  {\n    "id": "101",\n    "name": "Dev"\n  }\n]' }],
    faq: [{ question: 'What delimiter is expected?', answer: 'Commas are standard.' }],
    relatedTools: ['json-to-csv', 'json-formatter']
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    slug: 'json-to-yaml',
    category: 'json-data',
    description: 'Convert JSON documents into human-readable YAML configurations for Docker and Kubernetes.',
    shortDescription: 'Convert JSON into clean YAML format.',
    icon: 'FileText',
    keywords: ['json to yaml', 'convert json to yaml'],
    primaryKeyword: 'JSON to YAML',
    relatedKeywords: ['convert JSON to YAML', 'Kubernetes YAML generator'],
    status: 'active',
    processingMode: 'client',
    component: 'JsonToYaml',
    seoTitle: 'JSON to YAML Converter Online | HMDevTools',
    seoDescription: 'Convert JSON structures to YAML configurations instantly for Kubernetes and Docker.',
    howItWorks: 'Paste JSON content to generate formatted YAML output.',
    features: ['Clean 2-space YAML indentation', 'Supports nested structures'],
    useCases: ['Converting JSON configs to Kubernetes manifests'],
    examples: [{ title: 'JSON to YAML', input: '{"service":"web"}' }],
    faq: [{ question: 'Which YAML version is generated?', answer: 'YAML 1.2 compliant.' }],
    relatedTools: ['yaml-to-json', 'json-to-xml']
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    slug: 'yaml-to-json',
    category: 'json-data',
    description: 'Convert YAML configuration files into valid JSON data structures.',
    shortDescription: 'Convert YAML configs into valid JSON.',
    icon: 'FileJson',
    keywords: ['yaml to json', 'convert yaml to json'],
    primaryKeyword: 'YAML to JSON',
    relatedKeywords: ['parse YAML online', 'convert YAML to JSON'],
    status: 'active',
    processingMode: 'client',
    component: 'YamlToJson',
    seoTitle: 'YAML to JSON Converter Online | HMDevTools',
    seoDescription: 'Parse YAML configurations into formatted JSON objects in your browser.',
    howItWorks: 'Paste YAML key-value pairs to calculate equivalent JSON data.',
    features: ['Parses nested structures', 'Strips comments'],
    useCases: ['Converting CI/CD YAML files to JSON'],
    examples: [{ title: 'YAML to JSON', input: 'name: HMDevTools' }],
    faq: [{ question: 'Are YAML comments included?', answer: 'No, comments are stripped.' }],
    relatedTools: ['json-to-yaml', 'json-formatter']
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    slug: 'json-to-xml',
    category: 'json-data',
    description: 'Convert JSON objects and arrays into structured, properly formatted XML documents with customizable root elements.',
    shortDescription: 'Convert JSON objects into formatted XML.',
    icon: 'FileCode',
    keywords: ['json to xml', 'convert json to xml'],
    primaryKeyword: 'JSON to XML',
    relatedKeywords: ['convert JSON object to XML', 'JSON XML transformer'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonToXml',
    seoTitle: 'JSON to XML Converter Online | HMDevTools',
    seoDescription: 'Convert JSON objects and arrays into structured XML documents with XML entity escaping.',
    howItWorks: 'Paste JSON payload and convert your data into clean XML markup.',
    features: ['Configurable root tag', 'Automatic XML entity escaping'],
    useCases: ['Converting REST API JSON payloads to SOAP web services'],
    examples: [{ title: 'JSON to XML', input: '{"title":"DevTools"}', output: '<?xml version="1.0"?>\n<root>\n  <title>DevTools</title>\n</root>' }],
    faq: [{ question: 'How are arrays handled?', answer: 'Arrays convert to repeated child tags.' }],
    relatedTools: ['xml-to-json', 'xml-formatter']
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    slug: 'xml-to-json',
    category: 'json-data',
    description: 'Parse XML documents and elements into structured JSON object representations.',
    shortDescription: 'Parse XML documents into JSON objects.',
    icon: 'FileJson',
    keywords: ['xml to json', 'convert xml to json'],
    primaryKeyword: 'XML to JSON',
    relatedKeywords: ['parse XML online', 'convert XML to JSON object'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'XmlToJson',
    seoTitle: 'XML to JSON Converter Online | HMDevTools',
    seoDescription: 'Parse XML files and string documents into formatted JSON objects locally in your browser.',
    howItWorks: 'Paste XML content to parse tags and text nodes into JSON.',
    features: ['Parses XML tags, attributes, and text nodes'],
    useCases: ['Transforming legacy XML API responses into modern JSON'],
    examples: [{ title: 'XML to JSON', input: '<root><item>Hello</item></root>', output: '{\n  "root": {\n    "item": "Hello"\n  }\n}' }],
    faq: [{ question: 'How are attributes preserved?', answer: 'Extracted into @attributes key.' }],
    relatedTools: ['json-to-xml', 'xml-formatter']
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    slug: 'xml-formatter',
    category: 'json-data',
    description: 'Beautify and format unindented XML files with clean tag indentation.',
    shortDescription: 'Beautify and format XML markup.',
    icon: 'Code',
    keywords: ['xml formatter', 'beautify xml'],
    primaryKeyword: 'XML Formatter',
    relatedKeywords: ['beautify XML document', 'format XML online'],
    status: 'active',
    processingMode: 'client',
    component: 'XmlFormatter',
    seoTitle: 'XML Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format and beautify raw XML documents with clean tag indentation locally in your browser.',
    howItWorks: 'Paste raw XML string markup to auto-format element hierarchy.',
    features: ['Clean 2-space indentation', 'Preserves self-closing elements'],
    useCases: ['Formatting compressed XML API logs for inspection'],
    examples: [{ title: 'Raw XML Beautify', input: '<user><id>1</id></user>', output: '<user>\n  <id>1</id>\n</user>' }],
    faq: [{ question: 'Modifies XML values?', answer: 'No, tag content remains unchanged.' }],
    relatedTools: ['json-to-xml', 'xml-to-json']
  },

  // -------------------------------------------------------------
  // ENCODING & DECODING (8 Active)
  // -------------------------------------------------------------
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder',
    slug: 'base64-encoder',
    category: 'encoding',
    description: 'Encode plain text or multi-byte UTF-8 strings into standard Base64 format.',
    shortDescription: 'Encode plain text into Base64 format.',
    icon: 'Binary',
    keywords: ['base64 encoder', 'encode base64'],
    primaryKeyword: 'Base64 Encoder',
    relatedKeywords: ['encode to Base64', 'UTF-8 Base64 encoder'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'Base64Encoder',
    seoTitle: 'Base64 Encoder Online | HMDevTools',
    seoDescription: 'Encode text strings and UTF-8 characters to Base64 format locally in your web browser.',
    howItWorks: 'Paste text or strings to compute Base64 encoded output instantly.',
    features: ['UTF-8 support', 'Real-time encoding'],
    useCases: ['Encoding basic auth headers'],
    examples: [{ title: 'Text to Base64', input: 'Hello World', output: 'SGVsbG8gV29ybGQ=' }],
    faq: [{ question: 'Supports emojis?', answer: 'Yes, UTF-8 byte array handling ensures emojis encode correctly.' }],
    relatedTools: ['base64-decoder', 'url-encoder']
  },
  {
    id: 'base64-decoder',
    name: 'Base64 Decoder',
    slug: 'base64-decoder',
    category: 'encoding',
    description: 'Decode Base64 encoded strings back into human-readable text and UTF-8 characters.',
    shortDescription: 'Decode Base64 strings back to text.',
    icon: 'Binary',
    keywords: ['base64 decoder', 'decode base64'],
    primaryKeyword: 'Base64 Decoder',
    relatedKeywords: ['decode Base64 online', 'Base64 to text'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'Base64Decoder',
    seoTitle: 'Base64 Decoder Online | HMDevTools',
    seoDescription: 'Decode Base64 strings back into original text or UTF-8 characters safely in your browser.',
    howItWorks: 'Paste Base64 content to see decoded plain text.',
    features: ['Decodes standard and URL-safe Base64'],
    useCases: ['Decoding auth tokens'],
    examples: [{ title: 'Base64 to Text', input: 'SGVsbG8gV29ybGQ=', output: 'Hello World' }],
    faq: [{ question: 'Invalid Base64 input?', answer: 'Displays clear error message.' }],
    relatedTools: ['base64-encoder', 'jwt-decoder']
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder',
    slug: 'url-encoder',
    category: 'encoding',
    description: 'Encode characters in URLs into percent-encoded format for safe web transmission.',
    shortDescription: 'Percent-encode special characters in URLs.',
    icon: 'Link',
    keywords: ['url encoder', 'percent encoding'],
    primaryKeyword: 'URL Encoder',
    relatedKeywords: ['percent encode URL', 'encodeURIComponent online'],
    status: 'active',
    processingMode: 'client',
    component: 'UrlEncoder',
    seoTitle: 'URL Encoder (Percent Encoding) Online | HMDevTools',
    seoDescription: 'Encode query parameters and URLs using RFC 3986 percent-encoding in your browser.',
    howItWorks: 'Paste query values to encode special characters.',
    features: ['encodeURIComponent mode', 'Encodes spaces to %20'],
    useCases: ['Encoding search queries'],
    examples: [{ title: 'Query Encoding', input: 'hello world', output: 'hello%20world' }],
    faq: [{ question: 'Difference between encodeURI and encodeURIComponent?', answer: 'encodeURI preserves URL structure chars.' }],
    relatedTools: ['url-decoder', 'url-parser']
  },
  {
    id: 'url-decoder',
    name: 'URL Decoder',
    slug: 'url-decoder',
    category: 'encoding',
    description: 'Decode percent-encoded URL strings back into plain unescaped text.',
    shortDescription: 'Decode percent-encoded URL strings.',
    icon: 'Link2Off',
    keywords: ['url decoder', 'percent decode'],
    primaryKeyword: 'URL Decoder',
    relatedKeywords: ['percent decode URL', 'decodeURIComponent online'],
    status: 'active',
    processingMode: 'client',
    component: 'UrlDecoder',
    seoTitle: 'URL Decoder Online | HMDevTools',
    seoDescription: 'Decode percent-encoded URL strings back into readable text locally in your browser.',
    howItWorks: 'Paste percent-encoded URL strings to decode %20.',
    features: ['Decodes percent sequences'],
    useCases: ['Decoding parameters from web logs'],
    examples: [{ title: 'Percent Decoded', input: 'hello%20world!', output: 'hello world!' }],
    faq: [{ question: 'Decodes + as spaces?', answer: 'Standard percent decoding supported.' }],
    relatedTools: ['url-encoder', 'url-parser']
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    category: 'encoding',
    description: 'Decode JSON Web Tokens (JWT) to inspect header claims, payload values, and expiration timestamps.',
    shortDescription: 'Inspect header, payload, and claims of JWTs.',
    icon: 'Key',
    keywords: ['jwt decoder', 'decode jwt'],
    primaryKeyword: 'JWT Decoder',
    relatedKeywords: ['decode JWT online', 'JWT payload inspector'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JwtDecoder',
    seoTitle: 'JWT Decoder & Claims Inspector Online | HMDevTools',
    seoDescription: 'Decode JSON Web Tokens safely in your browser. Inspect header claims and token expiration.',
    howItWorks: 'Paste a 3-part JWT token to view header and payload claims.',
    features: ['Decodes header and payload', 'Checks expiration timestamp'],
    useCases: ['Inspecting user roles in OAuth tokens'],
    examples: [{ title: 'Sample JWT', input: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.sig' }],
    faq: [{ question: 'Verifies signature?', answer: 'No, decoding extracts payload. Signature verification requires server keys.' }],
    relatedTools: ['base64-decoder', 'hash-generator']
  },
  {
    id: 'html-encoder',
    name: 'HTML Encoder',
    slug: 'html-encoder',
    category: 'encoding',
    description: 'Convert special HTML characters (&, <, >, ", \') into HTML entities.',
    shortDescription: 'Convert special characters into HTML entities.',
    icon: 'Code',
    keywords: ['html encoder', 'escape html'],
    primaryKeyword: 'HTML Encoder',
    relatedKeywords: ['escape HTML entities online', 'HTML entity encoder'],
    status: 'active',
    processingMode: 'client',
    component: 'HtmlEncoder',
    seoTitle: 'HTML Encoder (Entity Escaper) Online | HMDevTools',
    seoDescription: 'Escape special HTML characters into entity codes (&lt;, &gt;, &amp;) locally in your browser.',
    howItWorks: 'Paste raw HTML markup to escape reserved characters.',
    features: ['Escapes <, >, &, ", \'', 'Prevents XSS rendering'],
    useCases: ['Escaping user input for safe HTML display'],
    examples: [{ title: 'Escape Tags', input: '<div>Text</div>', output: '&lt;div&gt;Text&lt;/div&gt;' }],
    faq: [{ question: 'Why escape HTML?', answer: 'Prevents browsers interpreting text as tags.' }],
    relatedTools: ['html-decoder', 'url-encoder']
  },
  {
    id: 'html-decoder',
    name: 'HTML Decoder',
    slug: 'html-decoder',
    category: 'encoding',
    description: 'Convert HTML entities (&lt;, &gt;, &amp;) back into plain text.',
    shortDescription: 'Decode HTML entities back to plain text.',
    icon: 'Code',
    keywords: ['html decoder', 'unescape html'],
    primaryKeyword: 'HTML Decoder',
    relatedKeywords: ['unescape HTML entities', 'decode HTML entity codes'],
    status: 'active',
    processingMode: 'client',
    component: 'HtmlDecoder',
    seoTitle: 'HTML Decoder (Entity Unescaper) Online | HMDevTools',
    seoDescription: 'Convert HTML entity codes back into readable plain text in your browser.',
    howItWorks: 'Paste HTML entity strings to unescape codes.',
    features: ['Decodes named and numeric entities'],
    useCases: ['Reading unescaped HTML content'],
    examples: [{ title: 'Unescape HTML', input: '&lt;p&gt;Text&lt;/p&gt;', output: '<p>Text</p>' }],
    faq: [{ question: 'Supports numeric entities?', answer: 'Yes, both named and numeric.' }],
    relatedTools: ['html-encoder', 'url-decoder']
  },
  {
    id: 'unicode-converter',
    name: 'Unicode Converter',
    slug: 'unicode-converter',
    category: 'encoding',
    description: 'Convert text to Unicode escape sequences (\\uXXXX) and convert Unicode escapes back to text.',
    shortDescription: 'Convert text to \\uXXXX Unicode escape sequences.',
    icon: 'Binary',
    keywords: ['unicode converter', 'unicode escape'],
    primaryKeyword: 'Unicode Converter',
    relatedKeywords: ['convert text to Unicode escape', 'decode \\uXXXX online'],
    status: 'active',
    processingMode: 'client',
    component: 'UnicodeConverter',
    seoTitle: 'Unicode Escape Converter (\\uXXXX) Online | HMDevTools',
    seoDescription: 'Convert text and emojis to Unicode escape sequences (\\uXXXX) and back locally in your browser.',
    howItWorks: 'Switch between Encode and Decode modes to convert characters.',
    features: ['Supports surrogate pairs (emojis)', 'Bidirectional conversion'],
    useCases: ['Escaping special characters in JSON strings'],
    examples: [{ title: 'Text to Unicode', input: 'Hello 🚀', output: 'Hello \\ud83d\\ude80' }],
    faq: [{ question: 'Supports emojis?', answer: 'Yes, converted into surrogate pair escape codes.' }],
    relatedTools: ['base64-encoder', 'html-encoder']
  },

  // -------------------------------------------------------------
  // GENERATORS (4 Active)
  // -------------------------------------------------------------
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    category: 'generators',
    description: 'Generate bulk cryptographically secure UUID v4 (Universally Unique Identifiers).',
    shortDescription: 'Generate secure Version 4 UUIDs.',
    icon: 'Fingerprint',
    keywords: ['uuid generator', 'guid generator'],
    primaryKeyword: 'UUID Generator',
    relatedKeywords: ['RFC 4122 UUID v4', 'GUID generator online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'UuidGenerator',
    seoTitle: 'UUID v4 / GUID Generator Online | HMDevTools',
    seoDescription: 'Generate random RFC 4122 Version 4 UUIDs and GUIDs in bulk locally using Web Crypto.',
    howItWorks: 'Select quantity and format preferences to generate unique RFC 4122 v4 UUIDs.',
    features: ['Web Crypto API randomness', 'Bulk generation up to 100'],
    useCases: ['Generating database primary keys'],
    examples: [{ title: 'Single UUID', output: 'f47ac10b-58cc-4372-a567-0e02b2c3d479' }],
    faq: [{ question: 'Are UUIDs random?', answer: 'Yes, generated using Web Crypto.' }],
    relatedTools: ['password-generator', 'hash-generator']
  },
  {
    id: 'password-generator',
    name: 'Random Password Generator',
    slug: 'password-generator',
    category: 'generators',
    description: 'Generate strong, customizable passwords with configurable length, symbols, and numbers.',
    shortDescription: 'Generate cryptographically strong passwords.',
    icon: 'ShieldCheck',
    keywords: ['password generator', 'random password'],
    primaryKeyword: 'Password Generator',
    relatedKeywords: ['strong password generator', 'random string generator'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'PasswordGenerator',
    seoTitle: 'Random Password Generator Online | HMDevTools',
    seoDescription: 'Generate strong random passwords locally using Web Crypto API with customizable character sets.',
    howItWorks: 'Adjust length slider and toggle character sets.',
    features: ['Web Crypto API randomness', 'Length control (8-64 chars)'],
    useCases: ['Generating database passwords'],
    examples: [{ title: '16 Char Password', output: 'k9#mP2$xL8!vQ4@z' }],
    faq: [{ question: 'Saved on a server?', answer: 'Never. Generated in client JS memory.' }],
    relatedTools: ['uuid-generator', 'hash-generator']
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    slug: 'lorem-ipsum-generator',
    category: 'generators',
    description: 'Generate placeholder text by paragraphs, sentences, or words for UI wireframes.',
    shortDescription: 'Generate placeholder text for design.',
    icon: 'FileText',
    keywords: ['lorem ipsum generator', 'placeholder text'],
    primaryKeyword: 'Lorem Ipsum Generator',
    relatedKeywords: ['dummy text generator', 'lorem ipsum text'],
    status: 'active',
    processingMode: 'client',
    component: 'LoremIpsumGenerator',
    seoTitle: 'Lorem Ipsum Generator Online | HMDevTools',
    seoDescription: 'Generate standard pseudo-Latin placeholder paragraphs or sentences for layout designs.',
    howItWorks: 'Select count and output type to produce placeholder text.',
    features: ['Generates paragraphs, sentences, or words'],
    useCases: ['Filling mockup layouts with text'],
    examples: [{ title: 'Sample Paragraph', output: 'Lorem ipsum dolor sit amet...' }],
    faq: [{ question: 'What is Lorem Ipsum?', answer: 'Standard placeholder text used in typography.' }],
    relatedTools: ['word-counter', 'case-converter']
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: 'hash-generator',
    category: 'generators',
    description: 'Generate SHA-256 and SHA-512 cryptographic hashes using the Web Crypto API, plus legacy MD5 checksums.',
    shortDescription: 'Generate SHA-256, SHA-512, and MD5 hashes.',
    icon: 'Key',
    keywords: ['hash generator', 'sha256 generator', 'md5 hash'],
    primaryKeyword: 'Cryptographic Hash Generator',
    relatedKeywords: ['generate SHA-256 hash', 'SHA-512 hash generator'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'HashGenerator',
    seoTitle: 'Cryptographic Hash Generator (SHA-256, SHA-512, MD5) | HMDevTools',
    seoDescription: 'Generate SHA-256, SHA-512, and MD5 hashes locally using the native Web Crypto API.',
    howItWorks: 'Enter text to calculate SHA-256, SHA-512, and MD5 hashes.',
    features: ['Web Crypto API for SHA-256/SHA-512', 'Legacy MD5 checksum'],
    useCases: ['Verifying file checksum integrity'],
    examples: [{ title: 'SHA-256 Digest', input: 'HMDevTools 2026' }],
    faq: [{ question: 'Is MD5 secure?', answer: 'MD5 is non-cryptographic. Use SHA-256 for security.' }],
    relatedTools: ['password-generator', 'uuid-generator']
  },

  // -------------------------------------------------------------
  // WEB & FORMATTING (8 Active)
  // -------------------------------------------------------------
  {
    id: 'url-parser',
    name: 'URL Parser',
    slug: 'url-parser',
    category: 'web-dev',
    description: 'Break down complex URLs into protocol, domain, port, pathname, query params table, and hash fragment.',
    shortDescription: 'Parse and inspect URL components & parameters.',
    icon: 'Compass',
    keywords: ['url parser', 'parse url'],
    primaryKeyword: 'URL Parser',
    relatedKeywords: ['parse URL query parameters', 'URL inspector online'],
    status: 'active',
    processingMode: 'client',
    component: 'UrlParser',
    seoTitle: 'URL Parser & Query Parameter Inspector | HMDevTools',
    seoDescription: 'Parse any web URL into hostname, path, port, scheme, and structured query key-value parameters.',
    howItWorks: 'Paste a web URL to extract structural parts and query parameters.',
    features: ['Extracts scheme, hostname, path', 'Key-value query table'],
    useCases: ['Inspecting campaign UTM tracking parameters'],
    examples: [{ title: 'Parsed Query', input: 'https://example.com/search?q=devtools' }],
    faq: [{ question: 'Must URL include protocol?', answer: 'Yes, http:// or https://.' }],
    relatedTools: ['url-encoder', 'url-decoder']
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    slug: 'html-formatter',
    category: 'web-dev',
    description: 'Beautify HTML markup with clean indentation, proper tag nesting, and line breaks.',
    shortDescription: 'Format and beautify HTML markup.',
    icon: 'Code',
    keywords: ['html formatter', 'beautify html'],
    primaryKeyword: 'HTML Formatter',
    relatedKeywords: ['beautify HTML markup', 'format HTML online'],
    status: 'active',
    processingMode: 'client',
    component: 'HtmlFormatter',
    seoTitle: 'HTML Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format raw unindented HTML tags with clean indentation locally in your web browser.',
    howItWorks: 'Paste raw HTML to auto-format nested elements.',
    features: ['Clean 2-space tag indentation', 'Preserves element nesting'],
    useCases: ['Beautifying minified HTML template strings'],
    examples: [{ title: 'HTML Formatting', input: '<div><p>Hello</p></div>' }],
    faq: [{ question: 'Supports self-closing tags?', answer: 'Yes, <img> and <br> handled correctly.' }],
    relatedTools: ['css-formatter', 'js-formatter']
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    slug: 'css-formatter',
    category: 'web-dev',
    description: 'Beautify messy CSS stylesheets with consistent selector spacing, indentation, and declaration rules.',
    shortDescription: 'Format and beautify CSS stylesheets.',
    icon: 'Palette',
    keywords: ['css formatter', 'beautify css'],
    primaryKeyword: 'CSS Formatter',
    relatedKeywords: ['beautify CSS styles', 'format CSS online'],
    status: 'active',
    processingMode: 'client',
    component: 'CssFormatter',
    seoTitle: 'CSS Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Beautify CSS stylesheets and rulesets with clean formatting and selector indentation.',
    howItWorks: 'Paste messy CSS rules to re-format declarations.',
    features: ['Formats selectors and declarations', 'Clean multi-line rulesets'],
    useCases: ['Formatting compressed CSS rulesets'],
    examples: [{ title: 'CSS Format', input: 'body{margin:0}' }],
    faq: [{ question: 'Supports media queries?', answer: 'Yes, formatted with clean indentation.' }],
    relatedTools: ['css-minifier', 'html-formatter']
  },
  {
    id: 'js-formatter',
    name: 'JavaScript Formatter',
    slug: 'js-formatter',
    category: 'web-dev',
    description: 'Beautify JavaScript/ECMAScript code with configurable indentation and syntax formatting.',
    shortDescription: 'Beautify JavaScript and ES6 code.',
    icon: 'FileCode2',
    keywords: ['js formatter', 'javascript beautifier'],
    primaryKeyword: 'JavaScript Formatter',
    relatedKeywords: ['beautify JavaScript online', 'format JS code'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsFormatter',
    seoTitle: 'JavaScript Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format and prettify JavaScript code strings directly in your browser memory.',
    howItWorks: 'Paste JavaScript code to produce clean formatted scripts.',
    features: ['Formats ES6+ syntax', 'Cleans statement indentation'],
    useCases: ['De-obfuscating single-line JS snippets'],
    examples: [{ title: 'JS Format', input: 'function test(){return true;}' }],
    faq: [{ question: 'Executes JS code?', answer: 'No, formatting is static text parsing.' }],
    relatedTools: ['js-minifier', 'html-formatter']
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    slug: 'markdown-to-html',
    category: 'web-dev',
    description: 'Convert Markdown text syntax into clean, sanitized HTML markup for web publishing.',
    shortDescription: 'Convert Markdown into sanitized HTML.',
    icon: 'FileText',
    keywords: ['markdown to html', 'convert markdown'],
    primaryKeyword: 'Markdown to HTML',
    relatedKeywords: ['convert Markdown to HTML online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'MarkdownToHtml',
    seoTitle: 'Markdown to HTML Converter Online | HMDevTools',
    seoDescription: 'Convert Markdown text into sanitized HTML markup locally with XSS security protection.',
    howItWorks: 'Paste Markdown content to render sanitized HTML markup.',
    features: ['Parses headings, bold, italic, lists', 'XSS sanitization'],
    useCases: ['Converting README files for web publishing'],
    examples: [{ title: 'Markdown to HTML', input: '# Title\n- Item', output: '<h1>Title</h1>\n<ul><li>Item</li></ul>' }],
    faq: [{ question: 'Sanitized against XSS?', answer: 'Yes, script tags and inline handlers stripped.' }],
    relatedTools: ['html-to-markdown', 'html-formatter']
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    slug: 'html-to-markdown',
    category: 'web-dev',
    description: 'Convert raw HTML elements and markup back into clean Markdown syntax.',
    shortDescription: 'Convert HTML tags into Markdown syntax.',
    icon: 'FileCode',
    keywords: ['html to markdown', 'convert html to md'],
    primaryKeyword: 'HTML to Markdown',
    relatedKeywords: ['convert HTML to Markdown online'],
    status: 'active',
    processingMode: 'client',
    component: 'HtmlToMarkdown',
    seoTitle: 'HTML to Markdown Converter Online | HMDevTools',
    seoDescription: 'Convert HTML markup into clean Markdown text syntax in your browser.',
    howItWorks: 'Paste HTML elements to transform tags into equivalent Markdown headers and lists.',
    features: ['Converts <h1>-<h6>, <p>, <a>, <ul>, <li> tags'],
    useCases: ['Converting HTML content into Markdown documentation'],
    examples: [{ title: 'HTML to MD', input: '<h2>Header</h2><p>Text</p>', output: '## Header\n\nText' }],
    faq: [{ question: 'Handles nested elements?', answer: 'Yes, nested lists and inline text preserved.' }],
    relatedTools: ['markdown-to-html', 'html-formatter']
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    slug: 'css-minifier',
    category: 'web-dev',
    description: 'Minify and compress CSS stylesheets by removing whitespace and comments.',
    shortDescription: 'Compress and minify CSS stylesheets.',
    icon: 'Minimize2',
    keywords: ['css minifier', 'minify css'],
    primaryKeyword: 'CSS Minifier',
    relatedKeywords: ['compress CSS online', 'minify CSS code'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'CssMinifier',
    seoTitle: 'CSS Minifier & Compressor Online | HMDevTools',
    seoDescription: 'Minify CSS stylesheets by stripping unneeded comments and whitespace to optimize file size.',
    howItWorks: 'Paste CSS rules to calculate minified stylesheet output.',
    features: ['Strips comments and whitespace', 'Calculates size savings %'],
    useCases: ['Optimizing CSS stylesheets for production'],
    examples: [{ title: 'CSS Minification', input: 'body {\n  margin: 0;\n}', output: 'body{margin:0}' }],
    faq: [{ question: 'Alters CSS selectors?', answer: 'No, only removes whitespace and comments.' }],
    relatedTools: ['css-formatter', 'js-minifier']
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    slug: 'js-minifier',
    category: 'web-dev',
    description: 'Compress and minify JavaScript code strings safely by stripping comments and line breaks.',
    shortDescription: 'Compress and minify JavaScript code.',
    icon: 'Minimize2',
    keywords: ['js minifier', 'javascript minifier'],
    primaryKeyword: 'JavaScript Minifier',
    relatedKeywords: ['compress JavaScript online', 'minify JS script'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsMinifier',
    seoTitle: 'JavaScript Formatter & Minifier | HMDevTools',
    seoDescription: 'Compress JavaScript code by removing unneeded comments and line breaks safely in your browser.',
    howItWorks: 'Paste JavaScript code to produce minified compressed script outputs.',
    features: ['Safely strips comments', 'Calculates file size savings %'],
    useCases: ['Minifying small JS utility scripts'],
    examples: [{ title: 'JS Minification', input: '// Comment\nfunction add(a, b) {\n  return a + b;\n}', output: 'function add(a,b){return a+b;}' }],
    faq: [{ question: 'Is JS executed during minification?', answer: 'Never, code is processed as static text parsing.' }],
    relatedTools: ['js-formatter', 'css-minifier']
  },

  // -------------------------------------------------------------
  // DATES & TIME (5 Active)
  // -------------------------------------------------------------
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    slug: 'unix-timestamp-converter',
    category: 'dates-time',
    description: 'Convert Unix epoch timestamps (seconds or milliseconds) to ISO dates, UTC, and local time.',
    shortDescription: 'Convert between Unix timestamps and human dates.',
    icon: 'Clock',
    keywords: ['unix timestamp converter', 'epoch converter'],
    primaryKeyword: 'Unix Timestamp Converter',
    relatedKeywords: ['convert epoch timestamp', 'timestamp to ISO date'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'UnixTimestampConverter',
    seoTitle: 'Unix Timestamp / Epoch Converter Online | HMDevTools',
    seoDescription: 'Convert seconds and milliseconds epoch timestamps to human-readable ISO and UTC dates.',
    howItWorks: 'Enter a numeric timestamp to calculate ISO 8601, UTC, and local calendar dates.',
    features: ['Auto-detects seconds vs milliseconds', 'Outputs UTC and ISO strings'],
    useCases: ['Debugging database timestamp integers'],
    examples: [{ title: 'Epoch to Date', input: '1700000000', output: '2023-11-14T22:13:20.000Z' }],
    faq: [{ question: 'What is Unix epoch time?', answer: 'Seconds elapsed since Jan 1, 1970 00:00:00 UTC.' }],
    relatedTools: ['timestamp-to-date', 'date-to-timestamp', 'timezone-converter']
  },
  {
    id: 'timestamp-to-date',
    name: 'Timestamp to Date',
    slug: 'timestamp-to-date',
    category: 'dates-time',
    description: 'Convert numeric Unix epoch timestamps directly into human-readable date formats across timezones.',
    shortDescription: 'Convert Unix epoch numbers to readable dates.',
    icon: 'Calendar',
    keywords: ['timestamp to date', 'epoch to date'],
    primaryKeyword: 'Timestamp to Date',
    relatedKeywords: ['epoch to human date', 'convert Unix timestamp to date'],
    status: 'active',
    processingMode: 'client',
    component: 'TimestampToDate',
    seoTitle: 'Timestamp to Date Converter Online | HMDevTools',
    seoDescription: 'Convert Unix timestamps into readable local and UTC date strings in your browser.',
    howItWorks: 'Paste a numeric timestamp integer to calculate calendar date and time.',
    features: ['Supports seconds and milliseconds', 'Displays UTC and local outputs'],
    useCases: ['Converting server log timestamps to readable dates'],
    examples: [{ title: 'Sample Epoch', input: '1609459200', output: '2021-01-01 00:00:00 UTC' }],
    faq: [{ question: 'Supports negative timestamps?', answer: 'Yes, dates prior to Jan 1, 1970.' }],
    relatedTools: ['unix-timestamp-converter', 'timezone-converter']
  },
  {
    id: 'date-to-timestamp',
    name: 'Date to Timestamp',
    slug: 'date-to-timestamp',
    category: 'dates-time',
    description: 'Pick or enter calendar dates to generate exact Unix epoch timestamp numbers in seconds and milliseconds.',
    shortDescription: 'Convert calendar date/time into epoch timestamps.',
    icon: 'CalendarCheck',
    keywords: ['date to timestamp', 'date to epoch'],
    primaryKeyword: 'Date to Timestamp',
    relatedKeywords: ['convert date to Unix epoch', 'generate epoch timestamp'],
    status: 'active',
    processingMode: 'client',
    component: 'DateToTimestamp',
    seoTitle: 'Date to Unix Timestamp Converter Online | HMDevTools',
    seoDescription: 'Convert any calendar date and time into Unix epoch seconds and milliseconds.',
    howItWorks: 'Select a date and time using the picker to generate epoch integers.',
    features: ['Interactive date picker', 'Calculates seconds and milliseconds'],
    useCases: ['Generating database query timestamp boundaries'],
    examples: [{ title: 'Date Input', input: '2026-01-01T00:00:00Z', output: '1767225600' }],
    faq: [{ question: 'Is UTC or local time used?', answer: 'Outputs both UTC ISO strings and Unix seconds.' }],
    relatedTools: ['unix-timestamp-converter', 'timestamp-to-date']
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    slug: 'timezone-converter',
    category: 'dates-time',
    description: 'Convert date and time values across global timezones (UTC, EST, PST, GMT, CET, IST, JST, AEST).',
    shortDescription: 'Convert dates across global timezones.',
    icon: 'Globe',
    keywords: ['timezone converter', 'utc to est', 'timezone calculation'],
    primaryKeyword: 'Timezone Converter',
    relatedKeywords: ['convert timezones online', 'global timezone converter'],
    status: 'active',
    processingMode: 'client',
    isNewTool: true,
    component: 'TimezoneConverter',
    seoTitle: 'Timezone Converter Online | HMDevTools',
    seoDescription: 'Convert date and time values across major world timezones locally in your browser.',
    howItWorks: 'Select a date, time, and target timezone to view formatted local time.',
    features: ['Supports major global timezones (UTC, EST, PST, GMT, IST, JST)', 'Browser Intl DateTimeFormat calculation'],
    useCases: ['Scheduling cross-border developer meetings', 'Converting server UTC logs to local time'],
    examples: [{ title: 'UTC to Tokyo Time', input: '2026-01-01 12:00:00 UTC', output: '2026-01-01 21:00:00 (Asia/Tokyo)' }],
    faq: [{ question: 'Handles daylight saving time?', answer: 'Yes, browser Intl API handles DST automatically.' }],
    relatedTools: ['unix-timestamp-converter', 'timestamp-to-date']
  },
  {
    id: 'cron-expression-helper',
    name: 'Cron Expression Helper',
    slug: 'cron-expression-helper',
    category: 'dates-time',
    description: 'Build, validate, and explain 5-field cron schedule expressions with plain English descriptions.',
    shortDescription: 'Build and explain cron schedule expressions.',
    icon: 'Clock',
    keywords: ['cron expression helper', 'cron builder', 'cron explainer'],
    primaryKeyword: 'Cron Expression Helper',
    relatedKeywords: ['explain cron expression', 'cron schedule builder online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'CronExpressionHelper',
    seoTitle: 'Cron Expression Helper & Explainer | HMDevTools',
    seoDescription: 'Build, validate, and parse standard 5-field cron schedule expressions into natural English explanations.',
    howItWorks: 'Enter a 5-field cron expression or select a schedule preset to view field breakdowns.',
    features: ['Natural language explanation', 'Field breakdown', 'Preset shortcuts'],
    useCases: ['Configuring backend cron jobs and scheduled tasks'],
    examples: [{ title: 'Every 15 Mins', input: '*/15 * * * *', output: 'Runs every 15 minutes.' }],
    faq: [{ question: 'Which cron dialect is explained?', answer: 'Standard 5-field crontab format.' }],
    relatedTools: ['unix-timestamp-converter', 'timestamp-to-date']
  },

  // -------------------------------------------------------------
  // REGEX (2 Active)
  // -------------------------------------------------------------
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    slug: 'regex-tester',
    category: 'regex',
    description: 'Test and debug JavaScript regular expressions with real-time match highlighting, regex flags, and capture groups.',
    shortDescription: 'Test regular expressions with instant match highlighting.',
    icon: 'Regex',
    keywords: ['regex tester', 'regular expression tester'],
    primaryKeyword: 'Regex Tester',
    relatedKeywords: ['regular expression matcher', 'test JS regex'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'RegexTester',
    seoTitle: 'Regex Tester & Matcher Online | HMDevTools',
    seoDescription: 'Test JavaScript regular expressions with real-time match highlighting, regex flags, and capture group diagnostics.',
    howItWorks: 'Enter your regular expression pattern, select flags (g, i, m), and paste a test string.',
    features: ['Supports flags (g, i, m)', 'Displays match count and index position'],
    useCases: ['Testing email and phone number validation patterns'],
    examples: [{ title: 'Email Matcher', input: '[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}' }],
    faq: [{ question: 'Which regex engine is used?', answer: 'Native V8 JavaScript RegExp engine.' }],
    relatedTools: ['regex-explainer', 'text-diff', 'word-counter']
  },
  {
    id: 'regex-explainer',
    name: 'Regex Explainer',
    slug: 'regex-explainer',
    category: 'regex',
    description: 'Break down complex regular expression tokens and syntax patterns into clear plain English explanations.',
    shortDescription: 'Explain regex patterns in plain English.',
    icon: 'HelpCircle',
    keywords: ['regex explainer', 'regex breakdown', 'explain regex online'],
    primaryKeyword: 'Regex Explainer',
    relatedKeywords: ['explain regex pattern', 'regular expression breakdown'],
    status: 'active',
    processingMode: 'client',
    isNewTool: true,
    component: 'RegexExplainer',
    seoTitle: 'Regex Explainer (Pattern Breakdown) | HMDevTools',
    seoDescription: 'Parse regular expression string patterns and explain character classes, anchors, and quantifiers in plain English.',
    howItWorks: 'Paste a regex string into the editor to generate token-by-token plain English explanations.',
    features: ['Explains anchors (^, $), character classes, and quantifiers', 'Tokenized breakdown display'],
    useCases: ['Understanding complex regular expressions copied from codebases', 'Learning regex syntax'],
    examples: [{ title: 'Email Regex Breakdown', input: '^[a-z]+@[a-z]+\\.[a-z]{2,}$' }],
    faq: [{ question: 'Supports JavaScript regex?', answer: 'Yes, standard JS regex token syntax is parsed.' }],
    relatedTools: ['regex-tester', 'text-diff']
  },

  // -------------------------------------------------------------
  // SQL & DATABASES (2 Active)
  // -------------------------------------------------------------
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    slug: 'sql-formatter',
    category: 'sql-databases',
    description: 'Format and beautify complex SQL queries (SELECT, INSERT, UPDATE, JOINs) with standardized keyword capitalization.',
    shortDescription: 'Format and beautify SQL queries.',
    icon: 'Database',
    keywords: ['sql formatter', 'beautify sql'],
    primaryKeyword: 'SQL Formatter',
    relatedKeywords: ['beautify SQL query', 'format SQL online'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'SqlFormatter',
    seoTitle: 'SQL Formatter & Beautifier Online | HMDevTools',
    seoDescription: 'Format SQL queries with clean keyword capitalization and statement indentation in your browser.',
    howItWorks: 'Paste raw or single-line SQL queries to format keywords (SELECT, FROM, WHERE, JOIN).',
    features: ['Capitalizes standard SQL keywords', 'Formats SELECT, JOIN, and WHERE clauses'],
    useCases: ['Formatting database query logs for inspection'],
    examples: [{ title: 'Raw SELECT Query', input: 'select u.id from users u where u.status="active"' }],
    faq: [{ question: 'Which SQL dialects supported?', answer: 'ANSI SQL, MySQL, PostgreSQL, SQLite, and SQL Server.' }],
    relatedTools: ['sql-minifier', 'json-formatter', 'text-diff']
  },
  {
    id: 'sql-minifier',
    name: 'SQL Minifier',
    slug: 'sql-minifier',
    category: 'sql-databases',
    description: 'Compress SQL statements to single-line string queries by stripping whitespace and comments.',
    shortDescription: 'Minify SQL queries to single line.',
    icon: 'Minimize2',
    keywords: ['sql minifier', 'compress sql query'],
    primaryKeyword: 'SQL Minifier',
    relatedKeywords: ['compress SQL statement', 'single line SQL converter'],
    status: 'active',
    processingMode: 'client',
    isNewTool: true,
    component: 'SqlMinifier',
    seoTitle: 'SQL Minifier & Query Compressor Online | HMDevTools',
    seoDescription: 'Compress SQL query statements to single-line strings by stripping unneeded comments and whitespace.',
    howItWorks: 'Paste raw multi-line SQL queries to produce compressed single-line SQL strings.',
    features: ['Strips single-line (--) and block comments', 'Compresses multiple whitespace spaces into one'],
    useCases: ['Minifying SQL query strings for inline code or ORM queries', 'Reducing log payload size'],
    examples: [{ title: 'SQL Minification', input: 'SELECT *\nFROM users\nWHERE id = 1;', output: 'SELECT * FROM users WHERE id = 1;' }],
    faq: [{ question: 'Does minifying alter query semantics?', answer: 'No, query logic remains unchanged.' }],
    relatedTools: ['sql-formatter', 'css-minifier', 'js-minifier']
  },

  // -------------------------------------------------------------
  // TEXT UTILITIES (5 Active)
  // -------------------------------------------------------------
  {
    id: 'word-counter',
    name: 'Word Counter',
    slug: 'word-counter',
    category: 'text-utilities',
    description: 'Count words, characters (with and without spaces), sentences, paragraphs, and estimated reading time.',
    shortDescription: 'Count words, characters, and reading time.',
    icon: 'AlignLeft',
    keywords: ['word counter', 'character counter'],
    primaryKeyword: 'Word Counter',
    relatedKeywords: ['count words online', 'character counter with spaces'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'WordCounter',
    seoTitle: 'Word & Character Counter Online | HMDevTools',
    seoDescription: 'Count words, characters (with & without spaces), lines, and reading duration in real-time.',
    howItWorks: 'Type or paste text into the input panel to see live word and character count stats.',
    features: ['Live real-time count', 'Calculates estimated reading duration'],
    useCases: ['Verifying blog post word counts', 'Checking meta description character limits'],
    examples: [{ title: 'Sample Text Stats', input: 'HMDevTools provides 50 developer utilities.' }],
    faq: [{ question: 'How is reading time calculated?', answer: 'Assuming average reading speed of 200 wpm.' }],
    relatedTools: ['case-converter', 'remove-duplicate-lines', 'whitespace-cleaner']
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    slug: 'case-converter',
    category: 'text-utilities',
    description: 'Transform text case between UPPERCASE, lowercase, camelCase, PascalCase, snake_case, kebab-case, and Title Case.',
    shortDescription: 'Convert text case (camelCase, snake_case, etc.).',
    icon: 'Type',
    keywords: ['case converter', 'camelcase converter'],
    primaryKeyword: 'Case Converter',
    relatedKeywords: ['convert string case', 'camelCase generator'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'CaseConverter',
    seoTitle: 'Text Case Converter (camelCase, snake_case) | HMDevTools',
    seoDescription: 'Convert text between programming variable styles (camelCase, snake_case, kebab-case, PascalCase) and text cases.',
    howItWorks: 'Paste text or variable names and select your target case format button.',
    features: ['Supports camelCase, PascalCase, snake_case, kebab-case, UPPERCASE, lowercase'],
    useCases: ['Converting database column names to camelCase JS properties'],
    examples: [{ title: 'camelCase Conversion', input: 'hello world', output: 'helloWorld' }],
    faq: [{ question: 'Supports multi-word strings?', answer: 'Yes, delimiters are handled correctly.' }],
    relatedTools: ['word-counter', 'remove-duplicate-lines']
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    slug: 'remove-duplicate-lines',
    category: 'text-utilities',
    description: 'Deduplicate text lists by removing repeated identical lines, with optional case sensitivity.',
    shortDescription: 'Remove duplicate lines from text lists.',
    icon: 'ListFilter',
    keywords: ['remove duplicate lines', 'deduplicate list'],
    primaryKeyword: 'Remove Duplicate Lines',
    relatedKeywords: ['deduplicate text list', 'filter unique lines'],
    status: 'active',
    processingMode: 'client',
    component: 'RemoveDuplicateLines',
    seoTitle: 'Remove Duplicate Lines Online | HMDevTools',
    seoDescription: 'Deduplicate text lists and filter unique lines instantly in your web browser.',
    howItWorks: 'Paste a list of text lines into the input area to filter duplicate entries.',
    features: ['Instant deduplication', 'Case-sensitive toggle'],
    useCases: ['Deduplicating lists of URLs or email addresses'],
    examples: [{ title: 'Deduplicate List', input: 'apple\nbanana\napple', output: 'apple\nbanana' }],
    faq: [{ question: 'Preserves line order?', answer: 'Yes, first occurrence of each line is kept.' }],
    relatedTools: ['whitespace-cleaner', 'word-counter', 'text-diff']
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    slug: 'text-diff',
    category: 'text-utilities',
    description: 'Compare two text strings or code files side-by-side to highlight added, removed, and modified lines.',
    shortDescription: 'Compare two text snippets for differences.',
    icon: 'GitCompare',
    keywords: ['text diff', 'compare text'],
    primaryKeyword: 'Text Diff',
    relatedKeywords: ['compare text online', 'diff checker tool'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'TextDiff',
    seoTitle: 'Text Diff & Code Comparator Online | HMDevTools',
    seoDescription: 'Compare two text blocks or code files side-by-side with line difference highlights in your browser.',
    howItWorks: 'Paste original text in left panel and modified text in right panel.',
    features: ['Line-by-line diff comparison', 'Color-coded addition (+)/removal (-) highlights'],
    useCases: ['Comparing two versions of a code snippet'],
    examples: [{ title: 'Text Difference', input: 'Left vs Right text blocks' }],
    faq: [{ question: 'Are files sent to a server?', answer: 'No, comparison logic runs 100% locally.' }],
    relatedTools: ['word-counter', 'remove-duplicate-lines', 'regex-tester']
  },
  {
    id: 'whitespace-cleaner',
    name: 'Whitespace Cleaner',
    slug: 'whitespace-cleaner',
    category: 'text-utilities',
    description: 'Strip leading, trailing, and duplicate spaces and empty lines from text lists.',
    shortDescription: 'Clean extra whitespace and empty lines from text.',
    icon: 'ListFilter',
    keywords: ['whitespace cleaner', 'trim spaces', 'clean extra spaces'],
    primaryKeyword: 'Whitespace Cleaner',
    relatedKeywords: ['strip extra spaces', 'clean duplicate whitespace'],
    status: 'active',
    processingMode: 'client',
    isNewTool: true,
    component: 'WhitespaceCleaner',
    seoTitle: 'Whitespace Cleaner & Space Trimmer | HMDevTools',
    seoDescription: 'Clean up extra whitespace, leading/trailing spaces, and duplicate blank lines from text snippets locally.',
    howItWorks: 'Paste text to trim leading/trailing whitespace and compress multiple spaces into single spaces.',
    features: ['Trims leading and trailing spaces per line', 'Strips empty lines'],
    useCases: ['Cleaning up copied text snippets from PDFs or web pages'],
    examples: [{ title: 'Clean Extra Spaces', input: '  Hello   world!  ', output: 'Hello world!' }],
    faq: [{ question: 'Does it remove newlines?', answer: 'Empty lines are stripped; content lines are kept clean.' }],
    relatedTools: ['remove-duplicate-lines', 'word-counter', 'case-converter']
  },

  // -------------------------------------------------------------
  // CODE CONVERSION (5 Active)
  // -------------------------------------------------------------
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    slug: 'json-to-typescript',
    category: 'code-conversion',
    description: 'Convert JSON object samples into strongly typed TypeScript interface or type definitions.',
    shortDescription: 'Convert JSON payload to TypeScript interfaces.',
    icon: 'FileCode',
    keywords: ['json to typescript', 'json to ts'],
    primaryKeyword: 'JSON to TypeScript',
    relatedKeywords: ['convert JSON to TS interface', 'generate TypeScript types'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonToTypescript',
    seoTitle: 'JSON to TypeScript Interface Converter | HMDevTools',
    seoDescription: 'Generate clean TypeScript interface and type definitions from JSON object payloads locally.',
    howItWorks: 'Paste a JSON payload to automatically derive TypeScript interface definitions.',
    features: ['Generates TypeScript interface syntax', 'Maps primitive types and arrays'],
    useCases: ['Generating TypeScript interfaces for REST API responses'],
    examples: [{ title: 'Generate Interface', input: '{"id":1,"user":"dev"}', output: 'export interface RootObject {\n  id: number;\n  user: string;\n}' }],
    faq: [{ question: 'Supports nested objects?', answer: 'Yes, generates typed properties for nested structures.' }],
    relatedTools: ['json-to-python', 'json-to-go', 'json-to-java', 'json-to-csharp']
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    slug: 'json-to-python',
    category: 'code-conversion',
    description: 'Convert JSON objects into Python dictionary or Dataclass models.',
    shortDescription: 'Convert JSON objects into Python Dataclasses.',
    icon: 'Code2',
    keywords: ['json to python', 'json to dataclass'],
    primaryKeyword: 'JSON to Python',
    relatedKeywords: ['convert JSON to Python Dataclass', 'generate Python class'],
    status: 'active',
    processingMode: 'client',
    isNewTool: true,
    component: 'JsonToPython',
    seoTitle: 'JSON to Python Dataclass Converter | HMDevTools',
    seoDescription: 'Convert JSON payloads into Python 3 Dataclass models and type-annotated code in your browser.',
    howItWorks: 'Paste JSON content to produce Python 3 @dataclass classes with typing annotations.',
    features: ['Generates Python 3.7+ @dataclass syntax', 'Maps int, float, str, bool, List'],
    useCases: ['Creating Python data models for FastAPI or Django backends'],
    examples: [{ title: 'Python Dataclass', input: '{"name":"item","price":19.99}' }],
    faq: [{ question: 'Python version supported?', answer: 'Standard Python 3.7+ dataclass syntax.' }],
    relatedTools: ['json-to-typescript', 'json-to-go', 'json-to-java']
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go',
    slug: 'json-to-go',
    category: 'code-conversion',
    description: 'Convert JSON payloads into Golang struct definitions with json field tags.',
    shortDescription: 'Convert JSON payloads into Go struct definitions.',
    icon: 'Cpu',
    keywords: ['json to go', 'json to golang struct'],
    primaryKeyword: 'JSON to Go',
    relatedKeywords: ['convert JSON to Go struct', 'generate Go struct'],
    status: 'active',
    processingMode: 'client',
    isNewTool: true,
    component: 'JsonToGo',
    seoTitle: 'JSON to Go Struct Generator | HMDevTools',
    seoDescription: 'Convert JSON objects into idiomatic Go struct types with json struct field tags.',
    howItWorks: 'Paste a JSON sample payload to output Golang struct type definitions.',
    features: ['Generates idiomatic Go struct types', 'Includes json field tags'],
    useCases: ['Generating Go structs for API unmarshaling'],
    examples: [{ title: 'Go Struct', input: '{"user_id":42}' }],
    faq: [{ question: 'Field tags included?', answer: 'Yes, fields include standard `json:"key"` tags.' }],
    relatedTools: ['json-to-typescript', 'json-to-python', 'json-to-csharp']
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java (POJO)',
    slug: 'json-to-java',
    category: 'code-conversion',
    description: 'Convert JSON payload samples into clean Java POJO class definitions with getters and setters.',
    shortDescription: 'Convert JSON to Java POJO classes.',
    icon: 'Code',
    keywords: ['json to java', 'json to pojo'],
    primaryKeyword: 'JSON to Java',
    relatedKeywords: ['convert JSON to Java POJO class', 'generate Java class'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonToJava',
    seoTitle: 'JSON to Java POJO Class Converter | HMDevTools',
    seoDescription: 'Convert JSON objects and arrays into Java POJO class models with private fields and getter/setter methods.',
    howItWorks: 'Paste a JSON payload and set root Java class name to generate Java POJO code.',
    features: ['Generates Java classes with private fields and getters/setters'],
    useCases: ['Creating Java DTO class models for Spring Boot backends'],
    examples: [{ title: 'Java POJO', input: '{"id":101,"name":"Dev"}', output: 'public class RootResponse {\n    private Integer id;\n    private String name;\n}' }],
    faq: [{ question: 'Generates getters and setters?', answer: 'Yes, public getField() and setField() methods generated.' }],
    relatedTools: ['json-to-csharp', 'json-to-typescript', 'json-to-python']
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C# (POCO)',
    slug: 'json-to-csharp',
    category: 'code-conversion',
    description: 'Convert JSON objects into C# POCO class definitions with System.Text.Json JsonPropertyName attributes.',
    shortDescription: 'Convert JSON to C# POCO classes.',
    icon: 'Code2',
    keywords: ['json to c#', 'json to csharp'],
    primaryKeyword: 'JSON to C#',
    relatedKeywords: ['convert JSON to C# class', 'generate C# POCO'],
    status: 'active',
    processingMode: 'client',
    isPopular: true,
    component: 'JsonToCsharp',
    seoTitle: 'JSON to C# POCO Class Converter | HMDevTools',
    seoDescription: 'Convert JSON payloads into idiomatic C# POCO classes with JsonPropertyName attributes locally in your browser.',
    howItWorks: 'Paste JSON content to produce C# class properties with JsonPropertyName attributes.',
    features: ['Generates C# auto-properties { get; set; }', 'Includes [JsonPropertyName("key")] attributes'],
    useCases: ['Creating C# DTO models for ASP.NET Core Web APIs'],
    examples: [{ title: 'C# POCO Class', input: '{"user_id":42}', output: 'public class RootObject {\n    [JsonPropertyName("user_id")]\n    public int UserId { get; set; }\n}' }],
    faq: [{ question: 'Which JSON attribute used?', answer: 'System.Text.Json.Serialization.JsonPropertyName.' }],
    relatedTools: ['json-to-java', 'json-to-typescript', 'json-to-go']
  }
];

export const getToolBySlug = (slug) => {
  return toolsRegistry.find(t => t.slug === slug || t.id === slug);
};

export const getToolsByCategory = (categorySlug) => {
  return toolsRegistry.filter(t => t.category === categorySlug);
};

export const getPopularTools = () => {
  return toolsRegistry.filter(t => t.isPopular);
};

export const getNewTools = () => {
  return toolsRegistry.filter(t => t.isNewTool || t.isNew);
};
